### ISSUE TITLE
Report js: Failed step execution time is always zero

### ISSUE THREAD

**Issue by FathimaHarris** [getgauge/html-report#10]
In the report js, which includes the execution time for each step, whenever a step fails, the execution time is always zero.

**Comment by Thunderforge** [comment]
This does not happen for me in the latest version of the plugin. If the scenario took at least one second to execute, the time listed is the expected duration of the scenario, instead of zero.

**Comment by kaustavdm** [comment]
The timestamp in html-report shows till seconds. If the steps get executed before 1000ms, then it shows as zero seconds. Most likely the failed tests have failed before 1000ms.
