### ISSUE TITLE
Special parameter content is getting cut off in the report

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#103]
**Expected behavior**
The special parameter content should be entirely visible.

**Actual behavior**
Special parameter content is getting cut off in the report.

**Steps to replicate**
1. In gauge-tests run basic_specs specification.
2. Hover over the step
```
Verify Console Details <table:resources/terminologies/specifications/basic_steps/one_scenario_passing/console_statistics.csv><table:resources/terminologies/specifications/basic_steps/one_scenario_passing/console_output.csv>
```
3. The content of 
```
<table:resources/terminologies/specifications/basic_steps/one_scenario_passing/console_statistics.csv>
```
is getting chopped off.
It would be ideal if the content would open in a separate tab when the parameter is clicked.

**Version**
```
Gauge version: 0.6.3 as on 4th November

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-10-27)
java (0.5.1.nightly-2016-10-26)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by BugDiver** [comment]
This issue has been fixed as part of #119 .
