### ISSUE TITLE
An exception in the after suite hook does not show until I click on a spec

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#104]
**Expected behavior**
The exception should be shown without clicking on any spec.

**Actual behavior**
It shows up after clicking on a spec

**Steps to replicate**
Run the specs of the project to replicate the issue.
[afterHookException.zip](https://github.com/getgauge/html-report/files/571306/afterHookException.zip)

**Version**
```
Gauge version: 0.6.3 - installed from build pipeline as on 4th November

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-10-27)
java (0.5.1.nightly-2016-10-26)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sguptatw** [comment]
Furthermore, the specifications have passed and the statistics reflect the same. Just wanted to re-confirm, currently an exception in after suite hook is not reflected in the statistics. Is this the expected behavior?

**Comment by mahendrakariya** [comment]
Fix should be available in nightly >= 2016-11-07

**Comment by sguptatw** [comment]
The statistics continue to reflect the specification status irrespective of the after suite failure. However the exit code is 1.
