### ISSUE TITLE
Clicking and refreshing on passed spec count not showing related information

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#105]
**Expected behavior**
When there are 0 passed specs, clicking and refreshing the page on the 0 passed spec count should show relevant information.

**Actual behavior**
The failed spec details are shown.

**Steps to replicate**
1. Download the project
[someruby.zip](https://github.com/getgauge/html-report/files/574533/someruby.zip)
2. Run the specs.
3. Click on the passed spec count which is 0. Now refresh the page. The details shown are of the failed spec

**Version**
```
Gauge version: 0.6.3 as on from pipeline 4th November

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-10-27)
java (0.5.1.nightly-2016-11-03)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by mahendrakariya** [comment]
Fix available in nightly >= 2016-11-09
