### ISSUE TITLE
The filter is not getting cleared properly

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#106]
**Expected behavior**
If the previous filter does not give any result, it should not affect subsequent filters.

**Actual behavior**
When a filter with no results is used, the subsequent filter yield no results.

**Steps to replicate**
1. Download the project
[someruby.zip](https://github.com/getgauge/html-report/files/574533/someruby.zip)

2. Run the specs
3. See the html report
4. In the filter type 'something' and press enter
`now you should not see any result`
5. Now type `Specification Heading`. This should give you a result, but it does not

**Version**
```
Gauge version: 0.6.3

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-10-27)
java (0.5.1.nightly-2016-11-03)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by mahendrakariya** [comment]
Fix available in nightly >= 2016-11-09
