### ISSUE TITLE
The spec list styling has an issue when there is a long exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#107]
**Expected behavior**
The spec names should be clearly visible

**Actual behavior**
The spec names are getting hidden

**Step to replicate**
1. with the project https://github.com/getgauge/gauge-test-apps/tree/master/projects
2. run gauge-test-apps/projects/web-apps-e2e/specs/html-report/withLongFailureError.spec
3. See the styling has an issue as showed in the image below
<img width="1440" alt="spec_list_styling_issue" src="https://cloud.githubusercontent.com/assets/6310197/20048800/251547ac-a4e5-11e6-85f6-8d8110452149.png">

**Version**
```
Gauge version: 0.6.3.nightly-2016-11-06

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-10-27)
java (0.5.1.nightly-2016-11-03)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by mahendrakariya** [comment]
Fix available in nightly >= 2016-11-09
