### ISSUE TITLE
Support for non-asterisk lists

### ISSUE THREAD

**Issue by tlempart** [getgauge/html-report#11]
Asterisk lists are used to define scenario steps, but sometimes there is a need to use lists for documentation purpose within scenario/specification. It would be great, if you can render non-asterisk lists (http://daringfireball.net/projects/markdown/syntax#list) properly.

**Comment by Thunderforge** [comment]
I think that this should be moved to the general [gauge project](https://github.com/getgauge/gauge/issues), since HTML is just reporting

**Comment by mahendrakariya** [comment]
This issue was moved to getgauge/gauge#279
