### ISSUE TITLE
Add bi-directional language support

### ISSUE THREAD

**Issue by sriv** [getgauge/html-report#110]
Refer to https://github.com/getgauge/gauge/issues/527, @boazberman has expressed interest in authoring specs in Hebrew.

This would need some changes in html-report:

- [ ] The layout should be RTL friendly, i.e. things that are right-justified for english need to be left-justified?
- [ ] Add support for internationalization of phrases/terms
- [ ] The navigation etc should be RTL friendly, i.e. sidebar could move to left.
- [ ] Search feature should work for RTL language terms/phrases

**Comment by boazberman** [comment]
I would be thrilled to help on this with some guidance. Thanks!

**Comment by sriv** [comment]
@boazberman - this will be mostly HTML/CSS/JS work, but I won't be surprised if some of it would trickle changes to Gauge core.

I think the first thing to do would be to get a sample report with Hebrew(or any other RTL language) and figure out which parts need to change. Would you be able to generate a report and attach it here please?

Please use the nightly version of HTML report, thanks!

**Comment by boazberman** [comment]
I don't have time at the moment, I hope I will have time to do it by the weekend. Thanks for the response!

**Comment by sriv** [comment]
Brilliant! Thanks for the effort.

**Comment by boazberman** [comment]
Please notice [](https://github.com/getgauge/gauge/issues/527#issuecomment-270024098)

**Comment by boazberman** [comment]
see [boazberman/guage-rtl](https://github.com/boazberman/gauge-rtl) I would realy want to help get this going. May I also refer you to look at [rtlcss](http://rtlcss.com/) or [postcss-rtl](https://www.npmjs.com/package/postcss-rtl) to help with the process

**Comment by ajoecker** [comment]
I would also like to see at least the second bullet, namely support of internationalization. Having the report localised to your language would be a huge benefit for any stakeholders, that are interested in Test results. 

I still do not understand the whole html-report flow, but would be happy to provide the translations for some languages

**Comment by zabil** [comment]
As a workaround you can override the default html theme to support other languages.
