### ISSUE TITLE
Should list failed scenarios before passed/skipped tests.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#112]
**Expected behavior**
Should list failed scenarios before passed/skipped tests.

**Actual behavior**
Listing it in the order specified in the spec

**Steps to replicate**
1. After running gauge-tests look at `specs/advanced_topics/refactoring/step_refactoring_through_command.html`

**Version**
```
Gauge version: 0.6.3.nightly-2016-11-27

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-11-27)
java (0.5.1.nightly-2016-11-21)
js (1.3.0)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-10-27)
```

**Comment by apoorvam** [comment]
Fix should be available in nightly >= 29.11.2016
