### ISSUE TITLE
JUnit messages not rendered properly

### ISSUE THREAD

**Issue by falkoschumann** [getgauge/html-report#117]
### Expected behavior
Display complete assert message of JUnit `org.junit.ComparisonFailure: expected:<foo> but was:<bar>`.

### Actual behavior
HTML entities are not escaped `org.junit.ComparisonFailure: expected: but was:`.

### Steps to reproduce
Create a simple step implementation with JUnits method `assertEquals`.

### Gauge version
Gauge version: 0.7.0

Plugins:
html-report (3.0.0)
java (0.5.1)
spectacle (0.0.2)
xml-report (0.1.3)

**Comment by apoorvam** [comment]
@falkoschumann I just tried reproducing this issue using the Gauge v0.7.0 and html-report plugin v3.0.0. I could see it working as expected:
Adding a failure as `assertEquals("foo", "bar");` in my step implementation gives following failure message in report:
`org.junit.ComparisonFailure: expected:<[foo]> but was:<[bar]>`

The text of `error_message` and `stacktrace` elements in report HTML are within `pre` tag, so it should work as expected. 

Can you tell us what versions of browser and OS are you using? I tried on Mac Sierra with Chrome v55 and Firefox 48 too.

**Comment by falkoschumann** [comment]
I reduce the code of my project to much. Here is a working example.

### Spec

    *   Test "foo bar foo"

### Step implementation

    @Step("Test <test>")
    public void test(final String test) {
        assertEquals("foo foo foo", test);
    }

### HTML

The generated code

    <pre>org.junit.ComparisonFailure: expected:<foo [foo] foo> but was:<foo [bar] foo></pre>

looks like 

    org.junit.ComparisonFailure: expected: but was:

The browser preserve whitespace but render valid tags in `<pre>`. `<[foo]>` is not a valid tag. `<foo [foo] foo>` is a valid tag but invisible.

Same issue in
*   Chrome 55
*   Firefox 50
*   Safari 10

**Comment by apoorvam** [comment]
Could reproduce this. Thanks for your detail explanation.

**Comment by apoorvam** [comment]
Fix should be available in html-report v3.0.1. 
@falkoschumann Please update plugin by `gauge --update html-report` and try this.

**Comment by falkoschumann** [comment]
It works. Thanks you.
