### ISSUE TITLE
Add Timestamps to the HTML-Reports

### ISSUE THREAD

**Issue by apoorvam** [getgauge/html-report#12]
On behalf of @aWdas: 

Timestamps should be added to the HTML-Reports, containing the following information:

When the step started; when the step ended; how long the step took
Total execution time (incl. when spec started, when spec ended)

**Comment by kaustavdm** [comment]
@apoorvam Is this still on the feature list? We show execution time. Do we need to show the timestamp when it started?

**Comment by apoorvam** [comment]
We need to show the execution time in milliseconds as well. Currently, a step which takes less than a second is shown as "00:00:00".

**Comment by mahendrakariya** [comment]
After discussing internally within the team, it was unanimously decided that displaying milliseconds for execution time is not required.
