### ISSUE TITLE
Ordered List

### ISSUE THREAD

**Issue by fdomingues-sky** [getgauge/html-report#123]
### Expected behavior
Correct markdown behaviour using ordered list.

### Actual behavior
All the list items have value 1, because in fact is generated one ordered list per item. 

###Example
![screen shot 2017-01-05 at 15 54 08](https://cloud.githubusercontent.com/assets/17125909/21686976/4bbdf4fa-d35f-11e6-9e9c-30c001baafdf.png)
<img width="1398" alt="screen shot 2017-01-05 at 15 50 04" src="https://cloud.githubusercontent.com/assets/17125909/21686981/4f9a11a8-d35f-11e6-88a2-48ba83996ddb.png">
![screen shot 2017-01-05 at 15 51 12](https://cloud.githubusercontent.com/assets/17125909/21686984/5248ab9e-d35f-11e6-8e8e-3f4c5d4808b9.png)

### Gauge version
Gauge version: 0.7.0

Plugins
-------
html-report (3.0.0)
java (0.5.1)

**Comment by fdomingues-sky** [comment]
this bug persists in the new version 3.0.1

**Comment by sriv** [comment]
should be available in nightly >= 19.3.2018

**Comment by sguptatw** [comment]
The issue is still replicable in version
```
Gauge version: 0.9.8.nightly-2018-03-14
Commit Hash: 0ac4700

Plugins
-------
html-report (4.0.4.nightly-2018-03-19)
js (2.2.0.nightly-2018-03-19)
```
**Steps to replicate**
* Create a gauge-js project
* Edit the example spec to have contents
```
# Specification Heading

This is an executable specification file. This file follows markdown syntax.
Every heading in this file denotes a scenario. Every bulleted point denotes a step.

To execute this specification, run

    gauge specs

* Vowels in English language are "aeiou".
    1. Item 1
    2. Item 2
    3. Item 3
    4. Item 4

## Vowel counts in single word

tags: single word

* The word "gauge" has "3" vowels.

1. Item 1
2. Item 2
3. Item 3
4. Item 4

## Vowel counts in multiple word

This is the second scenario in this specification

Here's a step that takes a table
    1. Item 1
    2. Item 2
    3. Item 3
    4. Item 4

* Almost all words have vowels
     |Word  |Vowel Count|
     |------|-----------|
     |Gauge |3          |
     |Mingle|2          |
     |Snap  |1          |
     |GoCD  |1          |
     |Rhythm|0          |
```
* gauge run specs from the command line
> Observe that the ordered list below the step `The word "gauge" has "3" vowels.`
![OrderedList.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46c7869e269086ada3e0ac57e611b2843b492d762a10e17132d0b57dbb1a2a070a094dff140c5f40faf9892ff7b56f75884e17ff933c0120996048e6edc00db513bb27814e80b4bd8f4dc9eb3425e088875d73.png)

**Comment by sriv** [comment]
fix for ordered lists in scenario should be available in nightly >= 20/03/2018

**Comment by sguptatw** [comment]
Known issue - Comments are not displayed in teardown and concepts https://github.com/getgauge/html-report/issues/62
