### ISSUE TITLE
Generate reports from saved execution data

### ISSUE THREAD

**Issue by apoorvam** [getgauge/html-report#124]
From [@saritapol13](https://github.com/saritapol13):

Ref issue: #120 

If report generation fails due to some reason, we'll have to re-run the tests again. There should be a way where this information is stored and by just running the html report plugin I should have a way to generate the reports. Currently I need to run the entire regression once again

**Comment by sguptatw** [comment]
**Assumptions**
------------------
* Gauge execution is successful.
* Html-report plugin is installed.

Test case
-----------
- [ ] I must be able to regenerate report without having to re-run the specs.
> - [ ] Report is successfully generated
> - [ ] Report generation failed
- [ ] Report regeneration must be taken care of when
> - [ ] Re-run failed tests.
> - [ ] Tagged execution 
> - [ ] Parallel execution
> - [ ] Folder execution
> - [ ] Scenario execution
> - [ ] Datatable driven execution
> - [ ] From IDE and command lines

**Comment by saritapol13** [comment]
Hi Sriv,

When can we expect this feature. Its really overhead to run the entire regression once again. 

Thanks,
Sarita

**Comment by sriv** [comment]
@saritapol13, an update: this is currently WIP, along with #99 and #131. #99 is a big one, since it brings in a lot of design changes. 

I hope to release this in the upcoming html-report release, so please watch out for an update.

**Comment by saritapol13** [comment]
@sriv Thank you taking this up in your release plan. This feature will definitely help users.

**Comment by nehashri** [comment]
- The html-report plugin now generates a `last_run_result.json` file in the root of the reports directory.
- There is also a symlink to the `html-report` executable in the same location as above.
- To regenerate the report
  - Navigate to the reports directory
  - run `./html-report --input=last_run_result.json --output="/some/path"`
    - In the above command you can specify `--theme=/theme/path` if you want to use custom report theme.
    - the output directory is created. Take care not to overwrite an existing directory

**Comment by sguptatw** [comment]
I am using the default theme. Just re-generating the report and getting the following error
```
inblr-<username>:html-report <username>$ ./html-report --input=last_run_result.json --out=../../abc
2017/04/17 10:14:45 Rel: can't make /Users/<username>/work/test/specs/folder relative to 
```

**Comment by sguptatw** [comment]
Fix available in 17/04 nightly

**Comment by sguptatw** [comment]
Getting the following error when a spec with parse error was executed and re-run
```
Getting Started with Gauge
==========================
table:specs/abc.csv

* Open the Gauge homepage "param"

Get Started111
--------------

Get Started112
--------------
tags:abc

* Go to Gauge Get Started Page
* Ensure installation instructions are available
* a failure

Get Started113
--------------
* Go to Gauge Get Started Page
* Ensure installation instructions are available
```
The error on the console is
```
inblr-<username>:html-report <username>$ ./html-report --input=last_run_result.json  --out=/Users/<username>/abc
2017/04/17 20:40:56 json: cannot unmarshal object into Go struct field spec.errors of type error
```

**Comment by sguptatw** [comment]
Gauge is executed successful. However when the HTML report plugin is getting killed, the json file is also not getting generated. This means I have to re-run the Gauge project with an increased timeout and repeat this process until it gets generated.
