### ISSUE TITLE
Code blocks are being escaped

### ISSUE THREAD

**Issue by andremota** [getgauge/html-report#128]
### Expected behavior
Code blocks shouldn't be escaped

### Actual behavior
Code blocks are being escaped

### Steps to reproduce
1. Create a spec with a code block:
```
Some Spec
=========
Code block (4 spaces at the beginning of each line):
    {
        "id": "some-value"
    }

(...)
```

2. Run the spec, the code block should look something like:
![Escaped Code Block](http://i.imgur.com/O5BHZAA.png)

### Gauge version
```
Gauge version: 0.8.0.nightly-2017-02-06

Plugins
-------
html-report (3.1.0)
java (0.6.0)
xml-report (0.2.0)
```
----------

I've already done some work on this to see what was the cause, don't know if it might help. 

I believe this is happening due to the markdown processing being applied to a escaped html string. If the html sanitization is applied after the markdown processing the problem might be solved?

As for my solution, I've changed the order of the `escapeHTML` and `parseMarkdown` on the templates  and changed the `escapeHTML` to use `microcosm-cc/bluemonday` html sanitize. Using this as a solution, i believe it also makes it possible to use some html tags to write the spec.

I can summit a PR if you wish.

**Comment by sriv** [comment]
@andremota - Thank you for the report and analysis!

I am not sure if you are aware, but we are redesiging the reports (see #99 for the discusssions and designs)

This is under development, but will likely take a week or two at the minimum. I feel, your PR would be valuable as it will serve your use case, till we release the new version.

Please, can you raise a PR? Also, please read the [Contribution Guidelines](https://github.com/getgauge/html-report/blob/master/CONTRIBUTING.md). Thanks.
