### ISSUE TITLE
Toggle all Gauge.write to be collapsed in report

### ISSUE THREAD

**Issue by tn4700** [getgauge/html-report#130]
### Feature Request
Gauge.write shows up in report as an collapse/expandable element. When used to log information as response, request and generated test data, the test report can get quite chaotic. It would be great to have the ability to toggle all Gauge.Write statements to be collapsed as default, so you could expand the ones you need to see.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
