### ISSUE TITLE
Ability to customize html report

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#131]
* Add a tab to the existing report
* Generate report for a given run
* Add new type of html report without having to use protobuf

**Comment by sriv** [comment]
> Generate report for a given run

This is addressed as part of #124

**Comment by nehashri** [comment]
[1] and [3] are addressed by exposing theming support for html report.

- The default theme resides in "$GAUGE_HOME/.plugins/html-report/<version>/themes/default`
- Custom theme can be cloned into any repository, and this path can be set in `GAUGE_HTML_REPORT_THEME_PATH` env var (or property in the .properties file).

Notes on theming:

- The view(HTML DOM) is generated using Golang's templating. The templates are stored in `views/partials.tmpl` in the theme root directory.
- The assets (css/js/images/fonts) should reside in the `assets` directory under the report theme root.
- The execution result schema is available in the html-report github repo at root level.

**Comment by sguptatw** [comment]
With the latest nightly getting

```
./html-report --input="last_run_result.json" --out="../tmp"
2017/04/10 09:39:11 open default/views/partials.tmpl: no such file or directory
```

**Version**
```
Gauge version: 0.8.4.nightly-2017-04-05

Plugins
-------
html-report (3.1.0.nightly-2017-04-07)
java (0.6.2)
```

**Comment by sguptatw** [comment]
- [x] able to change the logo and other styles without having to change the code.
- [ ] Currently there is no easy way to find the data model structure for customizing the report.

**Comment by sriv** [comment]
There is the [json schema](https://github.com/getgauge/html-report/blob/master/schema.json) for the output that is generated for the UI templates to consume.

**Comment by sguptatw** [comment]
We can add this to the documentation as well.
