### ISSUE TITLE
Missing Css ,fonts  , js and  images folder in gauge html reports.

### ISSUE THREAD

**Issue by Pihu14** [getgauge/html-report#132]
We are seeing the gauge report in the following way . This happens sometimes and not always .

<img width="897" alt="pastedgraphic-6" src="https://cloud.githubusercontent.com/assets/6413708/23436801/b16f3cba-fdc0-11e6-94c8-858b4ebc0fb3.png">

Gauge version: 0.7.0
Plugins
-------
html-report (3.0.1)
java (0.5.1)

**Comment by sriv** [comment]
Are you seeing this when the report is hosted in a remote server (ex. your CI server)? The css/js aren't loaded for some reason. Would it be possible to open your browser's console and watch for any errors when this occurs?

On a sidenote, you are on older version of gauge, gauge-java and html-report. You can try upgrading to the latest and see the list of updates available.

**Comment by Pihu14** [comment]
This is what i see in console 
Plugin [Html Report] with pid [53875] did not exit after 30.00 seconds. Forcefully killing it.
Specifications:	182 executed	58 passed	124 failed	0 skipped
Scenarios:	182 executed	58 passed	124 failed	0 skipped

Saw an open issue for the same 
https://github.com/getgauge/html-report/issues/120
and hence increased the plugin_kill_timeout = 30000(orignal was 10000)

**Comment by sriv** [comment]
Does increasing the timeout fix this for you? we have some performance improvements addressed as part of html-report [v3.1.0](https://github.com/getgauge/html-report/releases/tag/v3.1.0)

You will need to update Gauge (latest is 0.8.1), and Gauge-java(0.6.1) in order to use html-report v3.1.0.
