### ISSUE TITLE
HTML report crashes while TableDriven spec is running in regression

### ISSUE THREAD

**Issue by saritapol13** [getgauge/html-report#135]
[HtmlReportCrashlogs.txt](https://github.com/getgauge/html-report/files/875298/HtmlReportCrashlogs.txt)
Hi,

When a table driven spec ( one with csv file) is running along with other specs, every time while the report generation for table driven spec is crashing.

If you just run that single spec it runs fine. 

### Expected behavior
Html report should be generated without issues

### Actual behavior
HTML report is crashing as below. Currently ulimit is set to 65536 on machine. Its a linux machine. I have attached the complete exception that is being reported

runtime: failed to create new OS thread (have 821 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime stack:
runtime.throw(0x767ce4, 0x9)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc43a93a400, 0xc443fc3fc0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x793a90, 0xc42001b500)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:1572 +0x132
runtime.startm(0xc42001b500, 0x100000001)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:1642 +0x181
runtime.handoffp(0xc42001b500)
/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:1680 +0x296
runtime.retake(0x139f89ad0d1e06, 0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:3722 +0x130
runtime.sysmon()
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:3649 +0x21c
runtime.mstart1()
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:1126 +0x11e
runtime.mstart()
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:1096 +0x64

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc4247d4b6c)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc4247d4b60)
	/usr/local/Cellar/go/1.7.3/libexec/src/sync/waitgroup.go:131 +0x97
github.com/getgauge/html-report/generator.GenerateReports(0xc42016e090, 0xc424770e60, 0x49, 0x49, 0x8e14a0)
	/tmp/src/github.com/getgauge/html-report/generator/generate.go:274 +0x474
main.createReport(0xc42010e0a8)
	/Users/stechops/Library/Application Support/Go Agent/pipelines/HTML_Report/htmlReport.go:124 +0xef
github.com/getgauge/html-report/listener.(*GaugeListener).processMessages(0xc42014f240, 0xc4201760e0)
	/tmp/src/github.com/getgauge/html-report/listener/gaugeListener.go:80 +0x228
github.com/getgauge/html-report/listener.(*GaugeListener).Start(0xc42014f240)
	/tmp/src/github.com/getgauge/html-report/listener/gaugeListener.go:60 +0xf3
main.createExecutionReport()
	/Users/stechops/Library/Application Support/Go Agent/pipelines/HTML_Report/htmlReport.go:85 +0xc3
main.main()
	/Users/stechops/Library/Application Support/Go Agent/pipelines/HTML_Report/main.go:28 +0x9c

goroutine 57 [syscall]:

**gauge -v
Gauge version: 0.8.1

Plugins
-------
html-report (3.1.0)
java (0.6.1)**

**Comment by sguptatw** [comment]
@saritapol13 : Unable to replicate the issue with Gauge version
```
Gauge version: 0.8.4.nightly-2017-04-05

Plugins
-------
html-report (3.1.0.nightly-2017-04-07)
java (0.6.2)
```
If you are still facing the problem can you help us with a sample project having the issue.
