### ISSUE TITLE
Giving a path ~/work/abc in re-generating the report is creating shortcut of ~ in the current folder

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#145]
_From @sguptatw on April 17, 2017 15:29_

**Expected behavior**
The root folder shortcut should not be created in the current folder.

**Actual behavior**
A shortcut is getting created in the current folder

**Steps to replicate**
Give the output with ~ in path
```
./html-report --input=last_run_result.json  --out=~/work/abc
```
Check the current directory. It has a shortcut to the folder ~

_Copied from original issue: getgauge/gauge#628_

**Comment by nehashri** [comment]
Use of '\~' as a shortcut to the home directory of the user is a feature of the shell executing the command. This is supported by most shells. However, programing languages do not understand this notation as they do not recognize it. '\~'s in filepaths when used in programs have no special meaning and are treated as any other non special character.

The same command can be executed as 
```
./html-report --input=last_run_result.json  --out ~/work/abc
```
or 
```
./html-report --input=last_run_result.json  --out=$HOME/work/abc
```
