### ISSUE TITLE
Timestamp steps 

### ISSUE THREAD

**Issue by riju91** [getgauge/html-report#165]
_From @jonathangiber on March 5, 2018 12:32_

### Expected behavior
As a developer, I would like see a timestamp when each Gauge step is started in order to be able to correlate with different logs

_Copied from original issue: getgauge/gauge-java#132_

**Comment by jonathangiber** [comment]
Any news on this one?

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
