### ISSUE TITLE
The number in Comments on html report always show as "1".

### ISSUE THREAD

**Issue by amoslovePython** [getgauge/html-report#166]
### Expected behavior
The number should be correct on html report.

### Actual behavior
The number in Comments on html report always show as "1".

### Steps to reproduce
1. Write the comments under specification as a degital list;
2. Run specs
3. Open the html report

note： My gauge language is Java  and ide is Intellij IDEA

### Gauge version
```
$ gauge -v
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
html-report (4.0.3)
java (0.6.6)
js (2.1.0)
python (0.2.3)
spectacle (0.1.2)
xml-report (0.2.0)
```

![image](https://user-images.githubusercontent.com/24653016/37096937-29517126-2255-11e8-81b0-f524def4ab77.png)

![specs](https://user-images.githubusercontent.com/24653016/37096909-1905bb74-2255-11e8-8352-c56226d72d71.png)

**Comment by amoslovePython** [comment]
I find the same issue #123 , the my html-report version is 4.0.3

**Comment by sriv** [comment]
@amoslovePython I am closing this in favour of#123. This is a valid issue.
