### ISSUE TITLE
Two dynamic parameters under specs  but only show one in report.

### ISSUE THREAD

**Issue by amoslovePython** [getgauge/html-report#167]
### Expected behavior
Two dynamic parameters must be shown.

### Actual behavior
I define two dynamic parameters under specs, but the report only show one.

### Steps to reproduce
1. Please see my specs and html reports

specs:
```
# 批量还款
        |assetNo             |repayAmount|
        |--------------------|-----------|
        |4zYjULYF5ryqM8MAyskG|60         |
        |M0bb7gPPrMUueVhIbUqH|120        |

## 借款人主动还款

* 借款项目 <assetNo> 已到还款日期
* 项目应还金额 <repayAmount> 元
* 借款人有钱主动发起还款
```
html report
The report just display the first line dynamic parameter in table.
![image](https://user-images.githubusercontent.com/24653016/37097730-2b102ba4-2257-11e8-9c2b-22ba8205784f.png)

### Gauge version
```
$ gauge -v
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
html-report (4.0.3)
java (0.6.6)
js (2.1.0)
python (0.2.3)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by riju91** [comment]
@amoslovePython  Please click on the second row to get information about the second test case

**Comment by amoslovePython** [comment]
@riju91 thank you so much.
