### ISSUE TITLE
Screenshot is not captured on failure

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#172]
**Expected behavior**
The screenshot should be displayed on failure

**Actual behavior**
Screenshot is not displayed on failure

**Steps to replicate**
* Create a `gauge-js` project
* Add a new step
* Give the default implementation
* Run the specs `gauge run specs`
* Open the html-report
> No screenshot is displayed

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-28
Commit Hash: 66fc822

Plugins
-------
html-report (4.0.4.nightly-2018-03-28)
js (2.2.0.nightly-2018-03-28)
```

**Comment by sguptatw** [comment]
The screenshot version is `screenshot (0.0.1)`

**Comment by sguptatw** [comment]
**Note**
This issue occurs in JS when `throw "something"` i.e without an Error Object.
Screenshot is successfully captured when `throw new Error("something")`

**Comment by sguptatw** [comment]
There are 2 issues in this
- In a step, in JS project - when `throw new Error('something')` is used, screenshot is captured. `throw 'something'` Screenshot is not captured - https://github.com/getgauge/gauge-js/issues/134
- The current issue is to track `When there is an error in hooks, screenshot is not dispalyed.`

**Comment by Apoorva-GA** [comment]
I think the given `steps to replicate` and the next comment which says `When there is an error in hooks, screenshot is not displayed` are two different things.

Whats the actual issue here?

**Comment by sguptatw** [comment]
The actual issue is `When there is an error in the hooks, screenshot is not displayed`

**Steps to replicate**

* Create a gauge-js project
* Add a new hook implementation
* Give the implementation with error
* Run the specs gauge run specs
* Open the html-report

**Comment by Apoorva-GA** [comment]
This issue was moved to getgauge/gauge-js#149
