### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#178]
**Expected behavior**
Report generation should be seamless

**Actual behavior**
Getting
```
[html-report]2018/05/28 16:20:24 write .../testfolder/js/gauge-js-performance-usages/reports/html-report/specs/specs7/specs5/example2.html: bad file descriptor
[html-report]2018/05/28 16:20:24 write .../testfolder/js/gauge-js-performance-usages/reports/html-report/specs/specs9/specs6/example3.html: file already closed
```
**Steps to replicate**
* Project - https://github.com/sguptatw/gauge-js-performance-usages.git
* `gauge run`
> The above error occurs. This may be related to performance. This error may occur for a different number of specs on different machines.

**Comment by sriv** [comment]
on ubuntu, native I can run the suite fine.

**Comment by Apoorva-GA** [comment]
Fix should be available in html-report nightly >= 29/05/18
