### ISSUE TITLE
Create issues on an issue tracker from reports

### ISSUE THREAD

**Issue by zabil** [getgauge/html-report#181]
### Current behavior

The tester manually creates issues on an issue tracker for e.g. Github, JIRA when there's a test failure on the report and had to copy details like stack trace, step and scenario text etc.

### Expected behavior

Display a button against a test failure for e.g. "Create Github Issue" that will prepopulate error details so that it's much easier to report. This button must be configurable.

**Comment by ajoecker** [comment]
ideally this can be configured, so that it does not only allow to open GitHub Issue, but any other issue tracker

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
