### ISSUE TITLE
Add latest folder that points to the latest report path

### ISSUE THREAD

**Issue by andrew041** [getgauge/html-report#184]
### Behavior enhancement

It would be great to have a 'latest' folder for when running with 'overwrite_reports' set to false. This would help in a jenkins situation allowing a user to just point to the latest report while maintaining a history of reports.

**Comment by zabil** [comment]
Symlinking on windows maybe tough. Assuming this feature is most useful for CI/CD runs (*nix), perhaps detect the os and don't symlink on windows till go 1.11 release is out.

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
