### ISSUE TITLE
Use a relative path for 'GAUGE_HTML_REPORT_THEME_PATH'

### ISSUE THREAD

**Issue by andrew041** [getgauge/html-report#185]
###Behavior enhancement
Currently this property only uses an absolute path, but it would be very helpful to use a relative path instead. This would keep the behavior consistent with other properties used within Gauge along with making it easier when dealing with repos and multiple systems.

**Comment by jorgecunhamorsum** [comment]
It works with relative paths as well. At the moment I use it with "../GaugeReportsModels/themes/default" and no problems at all.

**Comment by nehashri** [comment]
@andrew041 This seems to work fine. Closing this issue. Please reopen it if you are still facing problems.
