### ISSUE TITLE
Screenshots captured in step and after step appear together

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#186]
**Expected behavior**
Screenshot after the step should appear below the step screenshot

**Actual behavior**
![screenshot_together](https://user-images.githubusercontent.com/6310197/43639766-f680c796-973a-11e8-8730-fffd85085b79.png)

**Steps to replicate**
* Create gauge-java project
`gauge init java`
* Add screenshot in after step hook
```
    @AfterStep
    public void AfterStep() {
        Gauge.writeMessage("Custom message for report");
        Gauge.captureScreenshot();
    }
```
* Add screenshot in step
```
    @Step("Vowels in English language are <vowelString>.")
    public void setLanguageVowels(String vowelString) {
        vowels = new HashSet<>();
        for (char ch : vowelString.toCharArray()) {
            vowels.add(ch);
        }
        Gauge.captureScreenshot();
    }
```
* Run the specs
> Open the html-report the screenshots appear next to each other

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-01
Commit Hash: 6aa1ce2

Plugins
-------
html-report (4.0.6.nightly-2018-07-30)
java (0.6.9.nightly-2018-08-02)
```

**Comment by shubhamsc** [comment]
One more issue similar to this
 - showing duplicate screenshot on step failure

![capture1](https://user-images.githubusercontent.com/34643008/44075091-0426e9b2-9fb9-11e8-870d-eb0a1ca77e7e.PNG)

**Comment by shubhamsc** [comment]
__After changes, everything would be in a separate block__

<img width="791" alt="screen shot 2018-08-15 at 2 01 40 am" src="https://user-images.githubusercontent.com/34643008/44117040-c25a216c-a02f-11e8-82ba-1a35e8e98b0f.png">
