### ISSUE TITLE
Markdown should be rendered in the report

### ISSUE THREAD

**Issue by SG57** [getgauge/html-report#19]
Gauge specializes in reading specifications as markdown, it's very common for other markdown to be present in the specifications Gauge doesn't care about that is there for rendering to nice looking HTML easily.

I feel html-report should make an attempt to parse any of this extraneous markdown into HTML to preserve the pretty rendering in the report.

![gauge_html_reports_markdown_bug1](https://cloud.githubusercontent.com/assets/4238696/10291426/9130628a-6b5e-11e5-9c00-d76709b5a0b2.jpg)

`Pegdown` is an open-source markdown-to-HTML library I am personally using and can vouch for that is incredibly simple to adapt into any code-base.  Parsing timeouts, extensions, etc. all are supported and should be configurable in the report generation as well.

**Comment by mahendrakariya** [comment]
Even we were internally discussing of adding this feature. Thanks for putting it here. We will be working on it soon.

**Comment by Thunderforge** [comment]
While I generally like this idea, I would like to request that markdown headers still be visually distinct from scenario and spec headers. If they appear the same way, it will be difficult to read the output.

Also, I would like to request a way to turn off markdown rendering (perhaps with a properties file alongside gauge.properties and java.proprties?)

**Comment by Thunderforge** [comment]
I thought about this a bit and decided that there really aren't any substantial cases when you would want to ignore markdown. Please ignore my request to be able to turn off markdown rendering (unless others would find it useful). I still think that markdown headers should be visually distinct from spec and scenario headers though.

**Comment by kaustavdm** [comment]
Currently html-report will parse comments in specification and scenarios as comments.

Specification headings and scenario headings are still shown differently. Only the comments are parsed as markdown.

I assume that is what was meant by @SG57 and @Thunderforge.

Closing this. Please feel free to reopen in case something is missing or, err, looks awkward.
