### ISSUE TITLE
Multi-line step format should be retained in the report

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#191]
**Expected behavior**
Multi-line step format should be retained in the report

**Actual behavior**
The html is of a multi-line step is rendered in a single line

**Steps to replicate**
* Open a spec with multi-line in spectacle
Or
* Run the spec and open the report
> The step is rendered in a single line.

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-22
Commit Hash: 3750b26
```
Child of https://github.com/getgauge/gauge/issues/265

**Comment by sriv** [comment]
newline need not be retained in the html-report, since the report takes care of word wrapping, and optimizes the viewport as per user's resolution setting (i.e. is responsive).
