### ISSUE TITLE
Gauge.writeMessage missing in step results

### ISSUE THREAD

**Issue by martinseidel** [getgauge/html-report#193]
Since Gauge Version 1.0.1 all <code>Gauge.writeMessage</code> in the method of a step aren't displayed in the html-report.
<code>Gauge.writeMessage</code> in <code>@BeforeStep</code> and <code>@AfterStep</code> are displayed as expected.
I only tested with the java plugin on CentOS7 and Ubuntu 18.04!

### Expected behavior
All <code>Gauge.writeMessage</code> are displayed.
![grafik](https://user-images.githubusercontent.com/8288004/45486952-25decc80-b75d-11e8-8d2a-dee26d1c186a.png)
```
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
html-report (4.0.5)
java (0.6.8)
screenshot (0.0.1)
xml-report (0.2.0)
```
### Actual behavior
No <code>Gauge.writeMessage</code> are displayed. 
![grafik](https://user-images.githubusercontent.com/8288004/45486392-32622580-b75b-11e8-8007-ae828b623cf4.png)
```
Gauge version: 1.0.1
Commit Hash: da2676b

Plugins
-------
html-report (4.0.5)
java (0.6.8)
screenshot (0.0.1)
xml-report (0.2.0)
```

### Steps to reproduce
1. Install gauge version 1.0.1
2. Initialise new Java project
```gauge init java```
3. Add a ```Gauge.writeMessage("bla")``` to ```StepImplementation.java```
For example:
```
...
    @Step("Vowels in English language are <vowelString>.")
    public void setLanguageVowels(String vowelString) {
        vowels = new HashSet<>();
        Gauge.writeMessage("BLAAAAAAAAAAA");
        for (char ch : vowelString.toCharArray()) {
            vowels.add(ch);
            }
        }
...
```
4. Run Spec
```gauge run specs/```
5. Open the ```index.html``` from directory ```report/html-report``` in different browsers

### Gauge version
```
Gauge version: 1.0.1
Commit Hash: da2676b

Plugins
-------
html-report (4.0.5)
java (0.6.8)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by sriv** [comment]
Hi @martinseidel - can you please try using the [latest nightly](https://bintray.com/gauge/html-report/Nightly/_latestVersion) of html-report? This should be fixed, and we will release soon, but it would be good to have it confirmed. thanks.

**Comment by martinseidel** [comment]
Hi @sriv it works! Thank you for the fast reaktion! Thumb up!
```
Gauge version: 1.0.1
Commit Hash: da2676b

Plugins
-------
html-report (4.0.6.nightly-2018-08-13)
java (0.6.8)
screenshot (0.0.1)
xml-report (0.2.0)
```
