### ISSUE TITLE
Update Gauge logo on the reports

### ISSUE THREAD

**Issue by zabil** [getgauge/html-report#203]
Change the logo on reports to the new one

![image](https://user-images.githubusercontent.com/54427/48166778-7a568200-e29e-11e8-852f-c13e58470a4c.png)

**Comment by Apoorva-GA** [comment]
Expected Report : 

<img width="1433" alt="screen shot 2018-11-13 at 09 51 18" src="https://user-images.githubusercontent.com/8462534/48390846-ef580a80-e729-11e8-8ae7-b7fa12e1e2e7.png">
Note : Difference is in font weight of the logo.
