### ISSUE TITLE
Add overall start and end date/time to report

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/html-report#21]
If someone looks at a Gauge report, it is not clear when the report was generated. Last night? A week ago? An hour ago? It's not clear. 

I'd like to request that the start time of the run (i.e. the time when `gauge specs` was executed) and the end time of the run (i.e. the time when `gauge specs` is completed) be added to the report.

**Comment by kaustavdm** [comment]
This is how it shows now in the top right area:

<img width="325" alt="screen shot 2016-01-06 at 3 50 51 pm" src="https://cloud.githubusercontent.com/assets/364832/12140365/57ffa39a-b48d-11e5-9368-c85a0b3965d6.png">
