### ISSUE TITLE
Report isn't generating any static files

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/html-report#214]
### Expected behavior
Should generate css/js files when generating report.

### Actual behavior
No static files are generated

### Gauge version
```
Gauge version: 1.0.4

Plugins
-------
flash (0.0.1)
html-report (4.0.7)
java (0.7.1)
js (2.3.4)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

**Comment by Apoorva-GA** [comment]
@haroon-sheikh We have taken down the html-report 4.0.7 release.
But I see that the css and js files are getting generated with the latest [nightly](https://bintray.com/gauge/html-report/Nightly/4.0.8.nightly-2019-02-15). Could you please verify this again?

Note : I tried running a sample java project created using `gauge init java`
```
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8.nightly-2019-02-15)
java (0.7.1)
js (2.3.5)
```

**Comment by nehashri** [comment]
@haroon-sheikh any updates?

**Comment by haroon-sheikh** [comment]
@nehashri I'm not able to reproduce this with latest nightly. Happy to close and reopen if it occurs again.
