### ISSUE TITLE
Html report should display properly in Jenkins

### ISSUE THREAD

**Issue by shubhamsc** [getgauge/html-report#219]
## Actual Behaviour 
Html report is not displaying properly in Jenkins. The pie-chart and screenshot images are missing. The symbol for copying file path and sorting by name and execution time also missing.

## Expected Behaviour
The report should display Properly.

## Steps to Reproduce
1. Create a java-maven project
2. Build the project in Jenkins
3. open HTML report from Jenkins workspace

The report will display:- 
<img width="1432" alt="Untitled" src="https://user-images.githubusercontent.com/34643008/55055502-27cd0500-5089-11e9-8985-744e0eb20036.png">

__Gauge version:__ 1.0.4
__Commit Hash:__ 3a9a647

Plugins
-------
html-report (4.0.6)
java (0.7.1)

**Comment by shubhamsc** [comment]
The report which is generated by building the project in Jenkins, If we open in localhost then everything seems good. the only when the report is opening from Jenkins, screenshots do not appear. If we try to open the image in new tab we can see that image as well.

**Comment by osandadeshan** [comment]
@shubhamsc : Also if there is an error, the screenshot also missing when the HTML report open from the Jenkins.

@zabil: I think if you guys can develop a jenkins reporting plugin for gauge, it would be very much helpful for the CI/CD pipeline. Because, we would like to have the trending test execution report and test execution summary when we click on a build number.

**Comment by zabil** [comment]
>  I think if you guys can develop a jenkins reporting plugin for gauge

You can use the XML report plugin and configure junit's plugin to do this.

**Comment by osandadeshan** [comment]
> > I think if you guys can develop a jenkins reporting plugin for gauge
> 
> You can use the XML report plugin and configure jenkins junit's plugin to do this.

I mean this kind of a summary.
![image](https://user-images.githubusercontent.com/9147189/55133339-5a3f3680-514b-11e9-81ae-126ba8b59a57.png)

**Comment by shubhamsc** [comment]
@osandadeshan The current issue is related to new version of Jenkins.
They've introduced new Content security policy which adds the below header to the response headers & the browsers simply decline to execute anything like stylesheets / Javascript.
`X-Content-Security-Policy: sandbox; default-src 'none'; img-src 'self'; style-src 'self';`
You need to follow these steps for solution :
1. Open the Jenkin home page.
2. Go to Manage Jenkins.
3. Now go to Script Console.
4. In that console paste below line and click on Run. `System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "")`
5. open html-report it will show as expected.

Note : After following the above steps if still it is not loading report properly then clear the browser cache and cookie and refresh the page.

For more information refer https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

**Comment by osandadeshan** [comment]
@shubhamsc 
Thanks for the solution. It worked well!

**Comment by gauravkhuraana** [comment]
Thanks a lot for this solution. Not sure how come its not being everywhere on the internet.. Thanks for the detailed solution and explanation behind it
