### ISSUE TITLE
Filter by tag in reporting

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/html-report#22]
_From @harinee on November 18, 2015 11:46_

There is currently no way to list the scenarios based on tags from my tests, in my report.
I would like to see how my tests are split based on the different tags that exist, across spec files.

Things that can help in reporting:
1. Count of scenarios across tags
2. Scenario heading under each tag
3. Ability to drill into the scenario to see the steps

_Copied from original issue: getgauge/gauge#254_

**Comment by mahendrakariya** [comment]
_From @kaustavdm on November 18, 2015 12:2_

Thanks for bringing this up @harinee. Looks like this depends on or is related to #113 and #97. We'll look into this, but seems like it is something we'll want to take up after a while.

**Comment by mahendrakariya** [comment]
_From @Thunderforge on November 18, 2015 19:48_

If this is just about reporting, perhaps it would be better to move this issue to the [html-report](https://github.com/getgauge/html-report) or [xml-report](https://github.com/getgauge/xml-report) projects?

**Comment by manuviswam** [comment]
@Thunderforge @mahendrakariya  I think the changes won't be just on the reporting side. AFAIK gauge core is not sending any information about the filtered steps. I may be wrong.

**Comment by mahendrakariya** [comment]
@manuviswam The reports have the data related to tags. We have to add the filtering.

**Comment by harinee** [comment]
Just to be clear, the tags report should work even when I do not want to execute some tests.
I could have marked some tests as 'Manual' which will not be executed, but still show up in the report of tag-filter.
As far as my knowledge goes, currently there is no way of obtaining the report without a test execution.
@mahendrakariya Are you sure the tags available in the reports right now will suffice such scenarios?

**Comment by Thunderforge** [comment]
@harinee I'm a bit confused with what you are describing. Say that your specs have two tags, `automated` and `manual` and there are no overlaps. If you run the command `gauge --tags "automated" specs`, only the specs tagged with `automated` will be executed. An equivalent command in this case would be `gauge --tags "!manual" specs`.

Are you saying that in these cases, the HTML output should show all specs that are in the `specs` folder including the ones tagged with `manual`?

If so, I don't think that this is a feature that is desired. We have nearly 1000 Gauge specs (largely migrated from Twist) with different tags. We run groups of 100 or so at a time, and so having 900 specs listed that were not run would make it very difficult to see the results of those that were run.

**Comment by kaustavdm** [comment]
I have implemented a basic filter in the html-report UI. It scans through specification headings, specification tags, scenario headings and scenario tags, and shows you the specifications and scenarios that match the search text, grouped by specifications.

![html-report-tag-filter](https://cloud.githubusercontent.com/assets/364832/11868670/8d6ef4ee-a4df-11e5-8442-66a7a629ff7d.gif)

**Comment by kaustavdm** [comment]
This is implemented and will be available in next release (which should be soon). Closing this for now.

**Comment by Thunderforge** [comment]
This is a very nice improvement, but does the header showing the number of specs need to take up so much screen real estate? That's my only real concern over it.

**Comment by mahendrakariya** [comment]
@Thunderforge Thanks a lot for the suggestion. We have reduced the header size via dee920ab22e4c312ad68fa66f4f5a4f611ef3eff.
