### ISSUE TITLE
Use the streamed messages in Gauge to generate reports

### ISSUE THREAD

**Issue by nehashri** [getgauge/html-report#221]
After https://github.com/getgauge/gauge/issues/1372 Gauge will send execution result at the end of each execution unit. Html report should use this streamed results to generate the reports instead of waiting for the end of suite execution.

**Comment by BugDiver** [comment]
The main reason for this was to avoid huge suite results. It was happening due to inline screenshot data in the result, and that has been handled by externalizing the screenshots (save as a file and send the path).
We would not need to implement it anymore.
