### ISSUE TITLE
Environment is showing as default/dev in the html-report after run with dev.properties file

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/html-report#222]
### Expected behavior
Environment should be showing as dev after run with dev.properties file

### Actual behavior
Environment is showing as default/dev after run with dev.properties file

### Steps to reproduce
1. Create gauge java maven project
2. Create a sub folder "dev" inside env folder
3. Create "dev.properties" file there.
4. Copy and paste all the things in default.properties to dev.properties
5. Run the project using maven command
`mvn test-compile gauge:execute -DspecsDir="specs/login.spec" -Denv="dev"`
6. Open html-report and check "Environment" label

### Screenshot
![image](https://user-images.githubusercontent.com/9147189/56181263-53a92e00-602a-11e9-9567-b8492b0470d1.png)

### Gauge version
```
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins

flash (0.0.1)
html-report (4.0.6)
java (0.7.2.nightly-2019-03-07)
js (2.3.2)
json-report (0.2.2)
python (0.3.4)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

**Comment by osandadeshan** [comment]
Same issue is in json-report also.

**Comment by Apoorva-GA** [comment]
This seems like an error while displaying the environments in html-report.
I notice that the right property file is picked up when `--env` flag is used but in html-report it shows `default` always.

Thanks for reporting we will be fixing it soon.

**Comment by osandadeshan** [comment]
@Apoorva-GA 
Thanks

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the latest gauge version 
``` Gauge version: 1.0.5.nightly-2019-04-22 ```
