### ISSUE TITLE
Display failed test while using retry mechanism

### ISSUE THREAD

**Issue by jonathangiber** [getgauge/html-report#230]
I would like to see the failed tests when using the retry mechanism in the report in order to fix possible flaky tests.

The way I see it, it could show a new field that won't affect the score of the report,.

**Comment by Korop** [comment]
+1

**Comment by zabil** [comment]
Unfortunately, from the way Gauge communicates to the html-report this information is not being passed and implementing this will require a big change, for this reason Gauge will not be implementing this. 

The work around would be to use some kind of logging mechanism to identify these failures.
