### ISSUE TITLE
The generated html/js files should be minified

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/html-report#232]
We currently run a suite of 1000+ specs and each report size is 60MB+ (without any screenshots). By removing the white space from these specs reduces the size by 1/3. 

We need to ship the report to remote location on every run.

### Expected behavior
The `html` and `js` files are minified or no extra white space lines.

### Actual behavior
There's a lot of extra whitespace in generated in html files. This increase the file size to be a lot higher.

### Gauge version
```
Gauge version: 1.0.5

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
java (0.7.2)
```

**Comment by haroon-sheikh** [comment]
The fonts directory itself is 3MB+, do we really need all of these fonts?

**Comment by NivedhaSenthil** [comment]
These are valid optimisations to be done, will be working on this soon. Thanks for bringing this up.
