### ISSUE TITLE
Feature request: support PlantUML

### ISSUE THREAD

**Issue by trung** [getgauge/html-report#239]
A picture can paint a thousand words. It would be super helpful to have the ability to support [PlantUML](https://plantuml.com) when rendering HTML Report

**Comment by nehashri** [comment]
@trung This looks like an enhancement that is only needed for projects testing web pages. Also, it would mean adding an external dependency to html-report which is not ideal. I am sure others may benefit from this, but I feel there are a lot of users who may not need this.

However, you can always create another plugin for Gauge with PlantUML. This will let you customise the reports as per your needs. 

You can always reach out to us to write your own custom report plugin. You can also try forking the existing html-report to help get started.
