### ISSUE TITLE
Failed to read proto message: proto: can't skip unknown wire type 6 for gauge_messages.Message

### ISSUE THREAD

**Issue by natsireef** [getgauge/html-report#240]
### Actual behavior
I got following error log continuously sometime when running test suite.
This just start happening recently.

> 2019/10/30 09:54:07 Failed to read proto message: proto: can't skip unknown wire type 6 for gauge_messages.Message
> 2019/10/30 09:54:07 Failed to read proto message: proto: can't skip unknown wire type 6 for gauge_messages.Message
> 2019/10/30 09:54:07 Failed to read proto message: proto: can't skip unknown wire type 6 for gauge_messages.Message
> 2019/10/30 09:54:07 Failed to read proto message: proto: can't skip unknown wire type 6 for gauge_messages.Message
> 2019/10/30 09:54:07 Failed to read proto message: proto: can't skip unknown wire type 6 for gauge_messages.Message

### Gauge version
I'm running with 
enable_multithreading = false
-DinParallel=true -Dnodes=4

Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
java (0.7.2)

**Comment by Debashis9012** [comment]
The same issue has been reported and fix is in progress. 
Kindly find more detailed discussion and feel free to provide additional information [here](https://github.com/getgauge/html-report/issues/213).
