### ISSUE TITLE
reports generation and specs

### ISSUE THREAD

**Issue by Nahask** [getgauge/html-report#249]
### Expected behavior
Hi,
I'm using specs outside the defined `GAUGE_PROJECT_ROOT` using a relative path to select my specs.

The scenarios reports for each specs should be inside the directory specified for my reports generation.

### Actual behavior
Instead, it seems that the directory, where my reports for each specs is set, is relative to the `gauge_specs_dir` directory, not inside it

### Steps to reproduce
1.  [set up a new gauge project](https://docs.gauge.org/getting_started/create-test-project.html?os=windows&language=javascript&ide=vscode)
2. move the specs folder outside the project directory
3. `gauge run ../specs/`

### Gauge version
```
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
java (0.7.3)
js (2.3.6)
json-report (0.3.2)
screenshot (0.0.1)
```

**Comment by BugDiver** [comment]
@Nahask Thanks for reporting it. I can replicate this at my end. We will discuss it report back.
