### ISSUE TITLE
Report screenshot failures clearly on report

### ISSUE THREAD

**Issue by zabil** [getgauge/html-report#257]
### Expected behavior
Clearly indicate that there was an error taking the screenshot using the default
screenshot handler in the screenshot sectionof the HTML when on headless environments.

Point to the relevant section of the documentation for implementing custom screenshot handlers.

### Actual behavior
Blank screenshot

### Steps to reproduce
1. Initialize a gauge project (basic one without custom screenshot handler)
2. Add a failing tests
3. Run tests on docker

### Gauge version
```
gauge -v
Gauge version: 1.0.7

Plugins
-------
dotnet (0.1.4)
html-report (4.0.10)
java (0.7.6)
js (2.3.10)
python (0.3.8)
ruby (0.5.3)
screenshot (0.0.1)
spectacle (0.1.4)
ts (0.0.5)
xml-report (0.2.3)
```

**Comment by NivedhaSenthil** [comment]
Fixed by #268
