### ISSUE TITLE
Add ability to see failed retries in html-report (using gauge native retries)

### ISSUE THREAD

**Issue by gadgadskiy** [getgauge/html-report#259]
Please add ability to attach failed steps or logs in html-report if test was passed after 2nd/3rd try using native gauge retrying mechanism. Currently we can see fails only in build log, but in report there's showing only last (successful) result. And it isn’t obvious that test is flaky.

### Steps to reproduce
1. Run test with retrying (`gauge run --max-retries-count=2` or `gauge:execute -Dflags=--max-retries-count=2` on TeamCity)
2. One of steps in test should fail first time and pass second time.

### Expected behavior
There's some mark or logs in html report that step was failed one time.

### Actual behavior
Nothing in report shows that there was failed tries.

### Gauge version
1.0.6+

**Comment by BugDiver** [comment]
The PRs have been raised to address the issue. The feature will be available in next release

Here are some  screenshots showing how this would look like

* When a scenario passes after few retries
<img width="620" alt="Screenshot 2020-04-23 at 1 11 27 PM" src="https://user-images.githubusercontent.com/15309877/80072999-a635f800-8564-11ea-997e-27f9d6deed0a.png">


* When a scenario fails even after max retries
<img width="620" alt="Screenshot 2020-04-23 at 1 13 32 PM" src="https://user-images.githubusercontent.com/15309877/80072907-830b4880-8564-11ea-91ea-ee9d3446fe43.png">

**Comment by olejkavn** [comment]
Will we have some options to add some data about failed attempts to html-report?
like some logs/screenshots etc?

**Comment by olejkavn** [comment]
@zabil  sure https://github.com/getgauge/html-report/issues/260

**Comment by dibyaranjan-pg** [comment]
Can someone confirm if this feature added to the json-report as well? A property to identify "Retried times" in JSON report

**Comment by zabil** [comment]
This feature is not available in JSON report. Please create and issue (or PR) at https://github.com/getgauge-contrib/json-report/issues
