### ISSUE TITLE
Add ability to see failed retries details

### ISSUE THREAD

**Issue by olejkavn** [getgauge/html-report#260]
https://github.com/getgauge/html-report/issues/259#issuecomment-618396729

### Expected behavior
Html report contains data from failed step.

Now we have logs hook which writes messages to html report with logs of http calls executed during test execution
Would be awesome to have this functionality with a retry mechanism like
additional blocks with failed steps stacktrace and data which can be posted to step if it have failed status

**Comment by zabil** [comment]
This will need a lot of changes in the messages passed between Gauge and the reporting plugin and will break compatibility for this reason Gauge won't be implementing this feature.
