### ISSUE TITLE
Handle Web Storage API Restrictions

### ISSUE THREAD

**Issue by JamesBream** [getgauge/html-report#262]
### Expected behavior
When I open a generated html report in a browser tab with restrictions to the Web Storage API I should still be able to operate the expandable (dropdown) execution blocks, filtering and sorting options.

### Actual behavior
In some cases, modern browsers may restrict access to Web Storage APIs which causes an uncaught DOMException in `main.js` when trying to access `sessionStorage` leading to display issues with the generated reports. Particularly the expandable execution blocks which may hide important test result data - but also searching and sorting functionality does not function.

```
Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at initializeFilters main.js:151:9
```

### Steps to reproduce
1. Open a generated report in a browser tab with CSP or iframe sandbox enabled
2. Check console for exception/try to expand (click +) on a dropdown execution block

This behaviour may also occur in some browsers where private/incognito browsing does not give access to web storage APIs.

### Gauge version
```
Gauge version: 1.0.8

Plugins
-------
html-report (4.0.10)
js (2.3.10)
screenshot (0.0.1)
```

While `sessionStorage` is used to persist searches and filtering across different pages to give the feel of an SPA, it shouldn't block JS execution if web storage APIs aren't available.

**Comment by sriv** [comment]
With #264 in place, html-report will fallback to using querystrings, which should fix this issue.

**Comment by JamesBream** [comment]
@sriv Any chance we could cut a patch release with this change? Looks like the version has been bumped to v4.0.12 in master by @BugDiver but that hasn't been released. Would be great to be able to improve our reporting with this change

**Comment by sriv** [comment]
yes, we should be making a release soon.

**Comment by sriv** [comment]
html-report 4.0.12 has been released and should be available for install once the changes propogate to the CDN.
