### ISSUE TITLE
Report doesn't display results when webdriver throws exception

### ISSUE THREAD

**Issue by jonathangiber** [getgauge/html-report#266]
Since I moved to openjdk, I get lot of crashed reports when I can't see which specs failed.

Here are some examples:
![1](https://user-images.githubusercontent.com/7656511/86230958-7a557500-bb9a-11ea-8809-bbc854e87976.PNG)
![2](https://user-images.githubusercontent.com/7656511/86230961-7b86a200-bb9a-11ea-96e9-c6f6288e0845.PNG)
![3](https://user-images.githubusercontent.com/7656511/86230966-7cb7cf00-bb9a-11ea-934a-26dd3c481f3a.PNG)

Already try using the following flags as recommend in some forums:
    options.addArguments("--disable-gpu");
    options.addArguments("--no-sandbox");
    options.addArguments("--disable-extensions");
    options.addArguments("--disable-dev-shm-usage");

Gauge version:
Your Environment Information -----------
	linux, 1.0.8, 28617ea
	html-report (4.0.11), java (0.7.7), json-report (0.3.1), spectacle (0.1.4), xml-report (0.2.3)
........................
Open-jdk: 13.0.2

**Comment by sriv** [comment]
Is this still an issue @jonathangiber ?

**Comment by jonathangiber** [comment]
I split the execution to 2 different ones so I'm not seeing this anymore, it was happening when I was initializing different web drivers (remote, incongnito, etc)

**Comment by sriv** [comment]
Thanks, I'll close the issue
