### ISSUE TITLE
Left hand pointing arrow is still there.

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/html-report#28]
**Screenshot:**
<img width="931" alt="screen shot 2016-01-06 at 9 38 07 am" src="https://cloud.githubusercontent.com/assets/2538874/12134828/5726eb88-b459-11e5-84a3-5b8a201e8353.png">

**Steps to reproduce:**
  * Generate reports
  * Click on the failed count (or skipped count)

**Comment by kaustavdm** [comment]
Can you check if this is getting loaded from cache or may be just an old build? The responsible pieces of code and files were removed in 1ef3679 and 76d612f4.

**Comment by mahendrakariya** [comment]
Unable to reproduce after update.
