### ISSUE TITLE
Reports generated with path containing space character and it prevents one click opening

### ISSUE THREAD

**Issue by ahmetgeymen** [getgauge/html-report#286]
### Expected behavior
I want to be able to access reports with one click on the terminal of the vs-code or any tool with terminal output on macOS.

### Actual behavior
It outputs with a line similar below. Path of the report files contain space character between date and time sections and prevents to one-click opening (cmd+click). Instead I would expect reports generated in path like `yyyy-mm-dd_hh.mm.ss/index.html`. It makes uncomfortable to access reports.

```
...
Successfully generated html-report to => /Users/.../Workspace/.../my-gauge-tests/reports/html-report/2021-12-28 15.54.17/index.html

Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 2.458s
```

### Gauge version
```
Gauge version: 1.4.2
Plugins
-------
html-report (4.1.2)
python (0.3.17)
screenshot (0.1.0)
```

**Comment by ahmetgeymen** [comment]
We may update the line below as the new format layout.
https://github.com/getgauge/html-report/blob/baa4f41d192296241ef14b0a1364cb1db80a8d5b/htmlReport.go#L31

**Comment by zabil** [comment]
That makes sense. Please feel free to raise a pull request to fix this.
