### ISSUE TITLE
bsdthread_register error on Mac OS 12.x and 13.x with Intel CPU

### ISSUE THREAD

**Issue by MLaeuchli** [getgauge/html-report#290]
This issue seems only to happen on Mac OS 12+ with an Intel CPU.
Mac Books wit a M1 CPU do not have this problem. 
Linux works fine as well.
I did not test this with any Windows devices.

### Expected behavior
Gauge Runs tests
Report is created

### Actual behavior
The following error appears:

```
fatal error: runtime: bsdthread_register error
runtime stack:
runtime.throw(0x14241cd, 0x21)
/usr/local/go/src/runtime/panic.go :616 +0x81 fp=0x7ff7bfefe228 sp=0x7ff7bfefe208 pc=0x1028d41
runtime.goenvs()
/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfefe258 sp=0x7ff7bfefe228 pc=0x10268c3
runtime.schedinit()
/usr/local/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfefe2c0 sp=0x7ff7bfefe258 pc=0x102b636
runtime.rt0_go(0x7ff7bfefe2f0, 0x1, 0x7ff7bfefe2f0, 0x1000000, 0x1, 0x7ff7bfefe6d0, 0x0, 0x7ff7bfefe6e0, 0x7ff7bfefe6ed, 0x7ff7bfefe724, ...)
/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfefe2c8 sp=0x7ff7bfefe2c0 pc=0x1050d24
Error starting plugin Html Report 4.0.8. Failed to connect to plugin. Timed out connecting to 127.0.0.1:49475
```
After that Gauge runs normally, but no html report is generated.

### Steps to reproduce
I created the following repository to quickly test it [bsdthread_rester-error repo](https://github.com/MLaeuchli/gauge-bsdthread_register-error)
1. Clone https://github.com/MLaeuchli/gauge-bsdthread_register-error.git
2. npm install
3. npm run gauge

### Gauge version

```
"@getgauge/cli": "^1.4.3"
```

**Comment by peschee** [comment]
@sriv Any change someone could take a look at this?

**Comment by sriv** [comment]
It's a bit tricky since I don't have a mac. I'll have to hunt for an intel mac. I'll try to see if I can lay my hands on one.

**Comment by chadlwilson** [comment]
> Error starting plugin Html Report 4.0.8. Failed to connect to plugin. Timed out connecting to 127.0.0.1:49475

HTML report `4.0.8` is built on an ancient golang version (`1.8` I believe), think that had issues on newer MacOS - update the plugin to latest version built on a newer golang? https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue

`gauge update html-report`

Will re-open if still relevant and that doesn't fix it.
