### ISSUE TITLE
gauge message and error messages not honoring line endings.

### ISSUE THREAD

**Issue by mulekej** [getgauge/html-report#34]
With the new html-report 2.0.0, when a step fails, the error message that displays in the error-message class does not honor the line endings placing the entire message on a single line. This doesn't appear to affect the stacktrace portion of the output.

This also affects the custom messages.

Example:
`
Gauge.writeMessage("Hello: \n World:");
`
 Should be:
`Hello:`
`World:`

Appears as:
`
Hello: World:
`

I don't know if the custom message worked before, but the error messages definitely did.

**Comment by kaustavdm** [comment]
@mulekej Which browser? I can reproduce in Firefox 43 64-bit.

**Comment by mulekej** [comment]
@kaustavdm Chrome 32 bit   v 43.0.2357.65

**Comment by kaustavdm** [comment]
I need to see if the newlines are retained as literal characters. If yes, they need to converted to `<br>` elements. If not, we need to retain them at the plugin level.

**Comment by kaustavdm** [comment]
The issue with stacktraces on single line was fixed before. Current changeset addresses the issue with gauge custom messages. Fix hould be available in html-report nightly >= 2016-06-30.
