### ISSUE TITLE
Specification names are not shown properly if the name exceeds certain limit

### ISSUE THREAD

**Issue by kashishm** [getgauge/html-report#36]
![screen shot 2016-01-29 at 3 10 20 pm 2](https://cloud.githubusercontent.com/assets/5915802/12672380/dea7a0a8-c69b-11e5-85e6-528ba4f454b2.png)

**Comment by kaustavdm** [comment]
This looks ugly! I see three ways:

1. Truncate specification name in the sidebar to fixed number of characters and show the full name as a tooltip on hover.
2. Make the sidebar horizontally scrollable (yukk...).
3. Force wrap the names to multiple lines (ermm...)

IMO, truncating makes more sense. What do you say?

**Comment by kaustavdm** [comment]
@kashishm This should have been taken care of by your commit and the changes pushed today. Can you confirm?

**Comment by kaustavdm** [comment]
This looks better now.

<img width="368" alt="screen shot 2016-03-22 at 2 29 12 pm" src="https://cloud.githubusercontent.com/assets/364832/13946417/82b3ca2e-f03a-11e5-8dce-620752cbafa5.png">
