### ISSUE TITLE
Template is shown instead of actual values til result.js loads

### ISSUE THREAD

**Issue by kashishm** [getgauge/html-report#37]
![screen shot 2016-01-29 at 3 15 32 pm 2](https://cloud.githubusercontent.com/assets/5915802/12672428/37b49aac-c69c-11e5-9752-1b96d391d88c.png)

**Comment by kaustavdm** [comment]
This happens because our reports are dependent on `result.js`. Angular needs that data to resolve the bindings. There is no way of solving this, apart from showing some sort of a loading message/progress bar/overlay till the data has loaded. Is that a desired solution?

**Comment by mahendrakariya** [comment]
Yes.

**Comment by kaustavdm** [comment]
@kashishm Can you test with the last commit? Close this issue if that solves it.

**Comment by kashishm** [comment]
With the latest commit, It showed white screen till result.js loads and showed the template for 2-3 seconds before rendering the data.

**Comment by kaustavdm** [comment]
Currently, the result file is loaded in header. This avoids content flashes, but we will have this issue for large test suites. The proper, but harder, solution is to render standalone pages for each spec and generate a meta JSON to search from. Till then, I will close this issue as the current fix _works_.
