### ISSUE TITLE
Comments are not shown at the expected location.

### ISSUE THREAD

**Issue by ocary** [getgauge/html-report#38]
Since upgrading from Gauge 0.2.? to 0.3.0, the HTML report is not showing comments that are in a spec in-line with the steps.  Instead, all comments are being shown at the top of the scenario.

# Example:
MySpec
========

tags:  MyTags

My comments about the spec as a whole.

My Scenario
---------------
setup the environment
* Step 1
* Step 2<br>
check stuff
* Step 3<br>
clean up environment
* Step 4

# Gauge 0.3.0, the HTML report shows
.....
setup the environment
check stuff
clean environment
Step 1
Step 2
Step 3
Step 4

# In Gauge 0.2.?, the HTML report showed
....
setup the environment
* Step 1
* Step 2<br>
check stuff
* Step 3<br>
clean up environment
* Step 4

Not having the comments "in-line" in the reports has created confusion in understanding specs that have a large number of steps.

Current version
Gauge 0.3.0
html-report 2.0.0
java 0.3.4
xml-report  0.1.2

Unfortunately, I don't have the exact version numbers prior to upgrading, but the reports in the old format have comments in-line.

**Comment by kaustavdm** [comment]
Looks fixed with c3e27dc. Reopen if this is reproduced.
