### ISSUE TITLE
Header contents overlap on small screens (e.g. iPad)

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/html-report#39]
The header at the top of the HTML report has elements that overlap when the browser window is small, or when shown on a device with a small screen. For instance, this is what it looks like when shown with a width of 1024 (the width of an iPad in landscape mode):

![1024](https://cloud.githubusercontent.com/assets/6200170/12892608/975b873c-ce52-11e5-9b8f-52c6fddac34f.PNG)

As you can see, the number skipped overlaps with a number of gray lines. Also, the number of total specs are beoverlapping with the pie chart.

This is what it looks like with a width of 768 (the width of an iPad in portrait mode):

![768](https://cloud.githubusercontent.com/assets/6200170/12892590/818efe0c-ce52-11e5-8e94-702a5a60b2a3.PNG)

At this point, the Skipped row has gone to a new line, and the total specs are completely overlapping the pie chart. Also, note that the space to the left of the pie chart hasn't changed.

This should be fixed so that we don't have any overlap at any screen size and appears better when reduced width is available. Also, vertical space should be considered as well.

**Comment by kaustavdm** [comment]
The current release of html-report does not have any responsiveness. We are currently working on making it respond to different screen sizes. The latest nightly of html-report has basic responsiveness baked in. We are waiting for some design feedback to make it better.
