### ISSUE TITLE
Data table doesnt show all the rows when duplicated

### ISSUE THREAD

**Issue by ApoorvaM** [getgauge/html-report#4]
When a cell value is repeated in a row, the data table skips that row and doesnt show it in report. But execution works fine.

Eg:

     |Product|Description       |
     |-------|------------------|
     |Gauge  |Gauge             |
     |Automation |Automation    |

**Comment by prateekbaheti** [comment]
Can reproduce it for a step
Eg:
````
* Step that takes a table
    |Product|Description     |
    |------|------------------|
    |Gauge  |Gauge            |
    |Automation |Automation |
````

**Comment by prateekbaheti** [comment]
Fixed in [commit](https://github.com/getgauge/html-report/commit/c283823d60c1399d4df0f7a29865d8138e97c2bf)
