### ISSUE TITLE
Show number of scenarios, instead of specs, in summary

### ISSUE THREAD

**Issue by harinee** [getgauge/html-report#42]
Currently, the top panel shows the summary of count of specs passed/failed.

Each scenario is a test. I would want to know how many of the total scenarios passed/failed.
When I see the total count of passes/failures, it makes more sense to have the number of scenarios.

**Comment by sriv** [comment]
The report should show both scenario and spec statistics, making it consistent with console output.

- Have total/passed/failed/skipped scenarios listed on the top below specs statistics.
- The pie chart should be enhanced to include breakup of specs and scenarios
- When viewing a specification (display scenario breakup - passed/failed/skipped for the spec, next to execution time)

**Comment by sguptatw** [comment]
When viewing a specification, I should be able to filter the passed failed and skipped scenarios.

**Comment by sguptatw** [comment]
A spec which has skipped with passed scenarios are not be discoverable. As the spec is marked green. The icon may be green with grey.
A spec which has skipped with failed scenarios  are not be discoverable. As the spec is marked red. The icon may be green with grey.

**Comment by mahendrakariya** [comment]
Duplicate of #92. Closing this issue.
