### ISSUE TITLE
Search for spec tags does not list scenarios

### ISSUE THREAD

**Issue by sriv** [getgauge/html-report#43]
## Actual

In the html-report, searching by a tag lists specifications, when there is a match at spec level tag. However, the search result filters out all the scenarios, assuming that there are not scenario matches, thus lists a blank spec.

## Expected

Search for a tag should list 

    (scenarios with matching tags) U (all scenarios from specs with matching tags)

**tldr**: spec tags apply to all scenarios that the spec contains and should be treated as such when searching.

**Comment by kaustavdm** [comment]
This will be available in html-report nightly for May 17.
