### ISSUE TITLE
Is it possible to add spec name in the header?

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/html-report#44]
Hi, 

Is it possible to add a spec name (filename) next to the specHeading and timestamp. It would help in finding out where exact to go when debugging especially when there's a lot of specs with similar heading names.

**Comment by apoorvam** [comment]
@haroon-sheikh We think the spec headings should describe the specific feature under test. You can try tagging your specs/scenarios based on the feature and search for all specs tagged with it in html-report. You can also filter only failed tests in report, while debugging. This will ease the searching/filtering in html-report.

**Comment by haroon-sheikh** [comment]
@apoorvam I completely understand what you're saying and I find that very useful. However, the change I'm asking here is different. I'd like to know which scenario is from which spec file name. So as a developer, I know where to go look for the specification straightaway.

**Comment by apoorvam** [comment]
Ah, I get it now. I think we can have spec filename to be displayed when you hover on a particular specification. Or, we should find a better way of showing filename.

**Comment by mahendrakariya** [comment]
@sguptatw This change should be available in `2.1.1.nightly-2016-04-22` build and the ones after that.
