### ISSUE TITLE
Formatting issues on long exceptions

### ISSUE THREAD

**Issue by ocary** [getgauge/html-report#45]
With HTML-Report v2.1.0, when there is a long exception the formatting is broken with different results across different browsers.

In Chrome v49 - the screenshot is not visible even if scrolled all the way to the right.
Screenshot from Chrome.
![image](https://cloud.githubusercontent.com/assets/6934721/14181908/aac7bff2-f72e-11e5-9927-8867511b2a3f.png)

In IE v11, the left sidebar is not visible, but the screenshot is available if you scroll all the way to the right

In Firefox v42, the left sidebar is visible and the screenshot is available if you scroll all the way to the right.  So Firefox technically is functioning but having to scroll to the right is cumbersome.  I think inline scrolling like is done for the stacktrace would be better.

Gauge version: 0.3.0
Plugins
html-report (2.1.0)
java (0.3.4)
xml-report (0.1.2)

**Comment by kaustavdm** [comment]
@ocary Thanks for reporting this. `html-report v2.1.0` is not optimized for browsers that do not support standard implementations of flexbox. Our focus was on getting a basic responsive layout out there. We will add vendor specific fallback support in the upcoming version. This issue should be fixed as a by-product of those changes.

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.
