### ISSUE TITLE
Clicking "Failed" icon shows passed specs if there are no failures

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#46]
When there are 0 failures, click the failed tests icon after clicking the passing tests icon. This still shows the tests that are passing

[index.html.zip](https://github.com/getgauge/html-report/files/198031/index.html.zip)

**Comment by kaustavdm** [comment]
@sguptatw Would the expected behaviour be to filter out that list and show that no tests have failed?

**Comment by sguptatw** [comment]
@kaustavdm Yes, this is the behavior similar the click on skipped tests when 0 tests are skipped.

**Comment by sguptatw** [comment]
@kaustavdm : If you observer in the html u have attached. If u click on the passing tests first and then the failing tests, it still shows the passing tests.

**Comment by kaustavdm** [comment]
@sguptatw Noted. Do you see any errors in the browser console when you click the failure icon?

**Comment by sguptatw** [comment]
It is currently showing the message
`Congratulations! You've gone all green and saved the environment!` if there are 0 failed tests and I click on failed tests. The messaging may be. `There are zero failed/skipped tests`

**Comment by sguptatw** [comment]
@kaustavdm : Please add the nightly number on this issue.
Also the latest nightly that is currently available is as on 02-06-2016

**Comment by kaustavdm** [comment]
These changes are available in [2.1.1.nightly-2016-06-27](https://bintray.com/gauge/html-report/Nightly/2.1.1.nightly-2016-06-27/view).
