### ISSUE TITLE
The default message about all tests green is missing

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#48]
With the following spec, the html report generated does not show the details by default
[html-report.zip](https://github.com/getgauge/html-report/files/200021/html-report.zip)

**Comment by mahendrakariya** [comment]
@sguptatw Could you please elaborate on what sort of details you are looking forward to?

**Comment by mahendrakariya** [comment]
Spoke to @sguptatw. What she means is `You've gone all green` message is missing.

**Comment by kaustavdm** [comment]
@sguptatw I can't seem to reproduce this any more. Works for me on html-report nightly (as of now) on Firefox and Chrome. Can you have a quick check and see if this is valid any more?

<img width="1440" alt="screen shot 2016-05-17 at 2 55 13 pm" src="https://cloud.githubusercontent.com/assets/364832/15317533/8a66e5cc-1c3f-11e6-8962-673d15ac8ad3.png">
<img width="1440" alt="screen shot 2016-05-17 at 2 55 30 pm" src="https://cloud.githubusercontent.com/assets/364832/15317534/8a6c13da-1c3f-11e6-9e72-1b6e4164a7fc.png">
