### ISSUE TITLE
Tests are executed with sub-set of table rows should be indicated in the report

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#50]
Expected behavior

If a sub-set of table rows are executed, the result html should highlight only the executed rows with green/red. The ones which are not-executed should be greyed out and not clickable.

Actual behavior

If a sub-set of table rows are executed, the result html highlights the ones which are not-executed also in green and are clickable.

Steps to reproduce
- Create a spec with table data
- Create a step using the table data.
- Implement the step
- Run the test with sub-set of table rows as parameters.
- The report highlights the rows that were not executed as green.

Gauge version

Gauge version: 0.4.0

Plugins

html-report (2.1.0)
java (0.3.4)

**Comment by mahendrakariya** [comment]
The data about which rows are skipped is not present in the `result.js` file. We can proceed on this only after we have this data.

An issue for this is present. Refer https://github.com/getgauge/gauge/issues/363

**Comment by apoorvam** [comment]
The dependent issue getgauge/gauge#363 is fixed and this is implemented in [commit](https://github.com/getgauge/html-report/commit/672188c6a2a8b37059557047ec72cce00fbd9131).

Fix should be available in nightly >= 26.10.2016

**Comment by sguptatw** [comment]
Failing scenario mentioned in https://github.com/getgauge/html-report/issues/64

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
