### ISSUE TITLE
Missing screenshot in chrome

### ISSUE THREAD

**Issue by pvskarps** [getgauge/html-report#51]
### Expected behavior
Expect to see a screenshot on failure in Chrome

### Actual behavior
We are not seeing screenshots in Chrome.  The screenshots appear fine in Firefox and IE

### Steps to reproduce
[reports.zip](https://github.com/getgauge/html-report/files/208786/reports.zip)
1.Unzip and open the attached report in Chrome
2.Go to the failed step and scroll to the far right.  No screenshot
3.Open same report in IE or Firefox scroll to the far right.  Screenshot is there.

### Gauge version
Gauge version: 0.4.0

Plugins
-------
html-report (2.1.0)
java (0.3.4)

Chrome version: 49.0.2623.110
Firefox version: 43.0.1
IE version: 11.0.9600.18230

**Comment by pvskarps** [comment]
Rolling back to html-report version 2.0.0 resolved the issue.  So it was for sure due to a change in 2.1.0

**Comment by apoorvam** [comment]
@pvskarps Thanks for the sample report attached. We found that the screenshot is available in HTML inspect, whereas it's not visible when the stack trace/error message is wide. This should be a styling issue which can be tracked in issue #69. 

Closing this for now.
