### ISSUE TITLE
Failures in before suite, after suite hook is not shown in reports

### ISSUE THREAD

**Issue by kashishm** [getgauge/html-report#55]

**Comment by sguptatw** [comment]
After spec shows failure of after suite.
It is also showing as red when there is a spec failure but no failure inside the hook.

**Comment by sguptatw** [comment]
Please add the nightly number

**Comment by apoorvam** [comment]
Fix should be available in nightly > 30-05-2016

**Comment by kaustavdm** [comment]
Phew! Finally we have one bug that did not come back. :relaxed:
