### ISSUE TITLE
It reports with an empty table

### ISSUE THREAD

**Issue by mohammed-amhend** [getgauge/html-report#6]
When create a step that takes a table with some empty cells, it reports with an empty table

|shopName   |city   |location                         |description      |category    |phoneNumber|
|                    |        |                                     | Any thing        |Classic      |0655744451   |

like this : 

![gauge test results](https://cloud.githubusercontent.com/assets/996111/8080616/e307f6cc-0f65-11e5-8832-900f4b7f63bc.jpg)
I tried to replace white spaces with some value like : None or Empty, but it stills give the same result.
apparently, it doesn't accept consequent equal values in the same row

**Comment by ApoorvaM** [comment]
Are you on html report plugin version 1.0.3? If not please update the plugin and check if it still happens. 

To update :
```
gauge --update html-report
```

**Comment by ApoorvaM** [comment]
Sorry, we could reproduce this issue on latest version of plugin. We'll make an update to the plugin soon.

**Comment by mohammed-amhend** [comment]
Thank you :)
