### ISSUE TITLE
Give more relevance to Gauge messages on failed steps

### ISSUE THREAD

**Issue by pablodcar** [getgauge/html-report#61]
When viewing the html report, the stacktrace of the exception does not give me a better understanding of the failure than the information I can collect before it happens and include it in the report.

i.e. I only use Gauge.writeMessage when it is worth to include information in the report. If I collect some environment information, values, logs and outputs I can include them in the report when an step fails using Gauge.writeMessage, but when I read the report this relevant information is below all the stacktrace that is shown as more important, which most of the time it is not the case.

Does it happens to others Gauge html-reports users? My enhancement proposal is to hide stacktrace by default and show messages first (with multiline support https://github.com/getgauge/html-report/issues/34). Any better Idea? 

See screenshot if it is more easy to understand.
![stepfailure](https://cloud.githubusercontent.com/assets/7429473/14763142/644d1904-0963-11e6-873c-28cfa3ba63ac.png)

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
