### ISSUE TITLE
Comments of teardown/context are not shown

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#62]
### Expected behavior

The comments of tear down should be shown 
### Actual behavior

comments of teardown are not shown
### Steps to reproduce

1.

```
Something
=========
are the comments shown

* something "" else
* def "something" has "this"

comments at scenario level
sfsdfsdf
--------

comments at scenario level
* This is showing as implemented
comments at scenario level
* def "something" has "this"

wwwwwwww
--------
* something "" else
* def "something" has "this"

___
somewhere
* Tear down step 1
step 1
* Tear down step 2
* Tear down step 3

__something else
```
1. Give dummy implementation to all
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by apoorvam** [comment]
This issue is dependent on [getgauge/gauge/#433](https://github.com/getgauge/gauge/issues/433).

**Comment by sguptatw** [comment]
Comments in concept are not shown

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
