### ISSUE TITLE
Allow markdown formatting in error messages

### ISSUE THREAD

**Issue by Buthrakaur** [getgauge/html-report#65]
### Expected behavior

Error messages should be markdown formatted so as we could use markdown formatting in failure messages.
### Actual behavior

The error message is rendered as simple monospaced text without markdown formatting.
![image](https://cloud.githubusercontent.com/assets/126757/14885909/56094cca-0d4e-11e6-96f3-3b483312d174.png)
### Steps to reproduce
1. create failing scenario with markdown formatted text as an error/exception message
2. run gauge
3. open html report => text isn't markdown-formatted
### Gauge version

```
Gauge version: 0.4.0

Plugins
-------
csharp (0.7.2)
html-report (2.1.0)
```

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
