### ISSUE TITLE
Style of a skipped scenario with context and tear down steps is wierd

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#66]
### Expected behavior
Style of a skipped scenario with context and tear down steps should also be grey

### Actual behavior
Style of a skipped scenario has white background for context and tear down

### Steps to reproduce
1. Create a spec
```
Specification Heading
=====================

* something

Vowel counts in multiple word
-----------------------------

This is the second scenario in this specification

Here's a step that takes a table

* somethingelse

___
* Tear down step
```
2. Give the implementation
```

    @Step("something")
    public void implementation2() {
    }


    @Step("Tear down step")
    public void TearDownStep21() {
    }
```
3. Run the spec
4. See the html report - 
Style of a skipped scenario has white background for context and tear down

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-04-24

Plugins
-------
html-report (2.1.1.nightly-2016-05-02)
java (0.3.4.nightly-2016-04-19)
xml-report (0.1.2)
```

**Comment by apoorvam** [comment]
This is not an issue as of [commit](https://github.com/getgauge/html-report/commit/92ad49b91f2f305b6ff9ff9a5758efb817c8c7cc). Fix should be available in nightly >= 01/06/2016
