### ISSUE TITLE
Html report not showing the screenshot

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#69]
### Expected behavior

If the configuration screenshot_on_failure = true, then screenshot should be visible in the html-report
### Actual behavior

The screenshot is available in the html, but not visible
### Steps to reproduce

1.

```
clone or checkout the github url
https://github.com/getgauge/gauge-test-apps.git
```
1. open projects in IntelliJ

```
change the value of `webdriver.chrome.driver` to point to the corresponding location.
```
1. mvn clean compile on the parent project
2. cd counter_web_app 

```
mvn tomcat:run
```
1. in another terminal cd web-apps-e2e

```
mvn install
```

One will see a failure
6. open the html-report

```
The screenshot is not visible. However it is available in the html
```
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-05-09

Plugins
-------
html-report (2.1.1.nightly-2016-05-10)
java (0.4.0.nightly-2016-05-09)
ruby (0.2.0.nightly-2016-05-09)
xml-report (0.1.2.nightly-2016-05-09)
```

**Comment by apoorvam** [comment]
Found that the screenshot is available in HTML inspect, whereas it's not visible when the stack trace/error message is wide. This should be styling issue for screenshot-container in html-report template.

**Comment by apoorvam** [comment]
Fix should be available in nightly >= 01/06/2016.

**Comment by sguptatw** [comment]
It is still replicable with the same steps mentioned above.

**Comment by kaustavdm** [comment]
Given the use case presented here, I have a nagging feeling that it may have something to do with the webdriver or the test case itself, and may not be a problem with html-report itself. The fix that @apoorvam added should show any image data if it is present.

I can't reproduce it normally with custom screenshot handlers or with screenshots taken by `gauge_screenshot`. Can it be that the particular use case mentioned here somehow results in a bad base64 encoded string, i.e., sends invalid image data? This needs some investigation.
