### ISSUE TITLE
Right hand side pane should reflect the search criteria

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#71]
**Expected behavior**
If the search criteria matches the spec heading it lists it in the search result it should reflect on the right side pane as well.

**Actual behavior**
If the search criteria matches the spec heading it lists it in the search result, but the right side pane shows the first spec

**Steps to replicate**
1. Create a spec - one.spec

```
Specification Heading
=====================
tags:top

a
---------------------------

tags: single word

* something

b
```
1. Create another spec - two.spec

```
something else
=====================
tags:top

not
---------------------------

tags: single word

* something

```
1. Give default implementations
2. run the tests
3. Select `Specification Heading`
4. Now search for something
5. It lists it in the search result, but the right side pane is still showing Specification heading

**Comment by mahendrakariya** [comment]
Fix available in nightly >= 2016-11-09
