### ISSUE TITLE
When the search criteria does not match anything it still shows the previously selected spec

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#72]
**Expected behavior**
If the search criteria does not match anything, it should not show anything on the rhs

**Actual behavior**
It shows only the spec heading

**Steps to replicate**
1. Create a spec
```
something else
=====================
tags:top

not
---------------------------

tags: single word

* something
```
2. search for `failed`
3. Now you previously selected spec

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-18

Plugins
-------
html-report (2.1.1.nightly-2016-05-19)
java (0.4.1.nightly-2016-05-17)
```

**Comment by kaustavdm** [comment]
This was addressed as a side effect of fixing #73. The fix should be available in html-report nightly >= 2016-06-28. I'll put this in QA for a formal closure.

**Comment by sguptatw** [comment]
Consider a filter which is applied when passed scenarios are selected. Choose a filter unique to the passing scenario. Now click on the failed icon. The RHS spec details are not getting cleared.

**Comment by kaustavdm** [comment]
@sguptatw Can you check with nightly >= 2016-07-06? Looks to me like 751ccf4 has addressed this.

**Comment by kaustavdm** [comment]
@sguptatw Sorry, false alarm. I see that this can be reproduced if there are failed specs. The choices here are:

- Clear the search box when clicking "Failed", "Passed" and "Skipped", or
- Add an override for these situations to perform another search *after* the "Failed", "Passed" or "Skipped" filters have been applied on click.

The first option is easier to implement. But I'm not sure if that is the desired behaviour. Please advice.
