### ISSUE TITLE
When search criteria is spec name it does not list scenarios under it

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#73]
**Expected behavior**
If the search criteria matches the name of the spec, it should show corresponding scenarios on the rhs

**Actual behavior**
It shows only the spec heading

**Steps to replicate**
1. Create a spec
```
something else
=====================
tags:top

not
---------------------------

tags: single word

* something
```
2. search for `something`
3. It does not show scenarios on the rhs

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-18

Plugins
-------
html-report (2.1.1.nightly-2016-05-19)
java (0.4.1.nightly-2016-05-17)
```

**Comment by sguptatw** [comment]
If a different `spec a` is selected before the filtering and now search for `spec b`. The rhs still shows `spec a`

**Comment by kaustavdm** [comment]
@sguptatw The spec display on right hand side is not supposed to change till you select a new spec from the left hand side list of specs, even if you searched for a new spec. Swapping off the currently displayed spec while starting to search will be too jumpy for our use case. Thoughts?

**Comment by kaustavdm** [comment]
@sguptatw Ah, I see what you mean there. Agreed.

If the search result does not match the current spec, it should be hidden.

**Comment by kaustavdm** [comment]
This was one of the most slippery issues ever in html-report. Phew.

@sguptatw This should be available in html-report nightly >= 2016-06-28

**Comment by sguptatw** [comment]
The specification heading of the previously selected spec is still visible. Does not change to the first available spec after filtering.

**Comment by kaustavdm** [comment]
@sguptatw As I [said](https://github.com/getgauge/html-report/issues/73#issuecomment-228773363), this changeset will be available in the nightly released today, >= 2016-06-28. The nightly you tested on, 2016-06-27 I presume, does not have the changes yet.

**Comment by kaustavdm** [comment]
Also, I had a few questions about whether this is the desired behaviour:

- In the changeset f224b04, the current specification is not changed if it is still part of the search result.
- If the search result does not have the current spec, the first spec from the search result is loaded.
- If the search result yields no response, clearing the field brings back the last spec that was displayed.

**Comment by sguptatw** [comment]
@kaustavdm :Thanks for the update, previously, I was referring to the search result not having the current spec. I will test it when the nightly will be available.

**Comment by sguptatw** [comment]
Currently if no specification is manually selected to load, a search does not select the first one in the result. It shows "No results found" when the search does not match any specs, but if the search matches some specs, it should load the first one from the result, if no specification has been loaded before.

**Comment by kaustavdm** [comment]
@sguptatw Can you check with nightly >= 2016-07-06 if you see desired behaviour?
