### ISSUE TITLE
Comma in a tag is neither searchable nor acts as a separator

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#74]
**Expected Behavior**
Comma in search of tags should either behave as  a separator of two tags or it should be treated as the criteria itself

**Actual behavior**
It does not do both

**Steps to replicate**
1. Create a spec

```
Specification Heading
=====================
tags:top

a
---------------------------

tags: single, word ~!@#,$%^&

* something

```
1. Run the spec
2. In the search criteria type single, word. It does not list the scenario.
3. Now remove the comma.
4. run the spec 
5. In search criteria type single, ~!@#,$%^&. It does not list anything either

**Comment by kaustavdm** [comment]
The search is fairly simple at this point. It only searches through the names of the tags and cannot match based on gauge's tag expression. It was a conscious decision, to ensure switching and sorting work better before the search itself is made more sophisticated. FWIW, we don't even have an index to look up to make searches faster. So, I'll consider this more of an enhancement, than a bug.
