### ISSUE TITLE
Concepts in context steps are shown in report before all scenarios

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#75]
**Expected Behavior**
The context steps are shown only as a part of scenario. Therefore concepts called in contexts also should be shown only as a part of the scenario.

**Actual Behavior**
It shows before all scenarios

**Steps to replicate**
1. Create a context
```
# Concept Heading
* step1
```
2. Create a spec
```
Specification Heading
=====================

* Concept Heading

scenario heading
---------------------------
* step1
```
3. Create implementation
```
    @Step("step1")
    public void implementation2() {
    }
```
4. Run the spec
5. See html report

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-31

Plugins
-------
html-report (2.1.1.nightly-2016-05-30)
java (0.4.1.nightly-2016-05-30)
```

**Comment by apoorvam** [comment]
Fix should be available in nightly >= 2016-06-02
