### ISSUE TITLE
Format the test steps to highlight parameters

### ISSUE THREAD

**Issue by nickdunand** [getgauge/html-report#76]
My test specifications, when viewed in the IntelliJ text editor, are a joy to read. The colouring of the steps - blue for normal text but green for parameters - adds hugely to the readability. Sadly this gets lost in both the IntelliJ HTML Preview and the test reports. 

It would be great if there was some diferentiation of parameters and text in the test reports.

![2016-06-01_13h32_39](https://cloud.githubusercontent.com/assets/3014151/15708186/691a6938-27fd-11e6-8aa4-ff444fa53e16.jpg)

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
