### ISSUE TITLE
Position of after spec hook in the report should be after the details of all the scenarios

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#77]
### Expected behavior

The hook details should be displayed in the order of their execution.
### Actual behavior

After spec hook is displayed above all scenarios.
### Steps to reproduce
1. Create a spec
2. Add the following hook

```
        @AfterSpec
        public void AfterSpec1(ExecutionContext context) throws Exception {
            throw new Exception("after spec ");
        }
```
1. Execute the specs and check the html-report.
2. The details are displayed at the top of the report
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by mahendrakariya** [comment]
Fix should be available in nightly >= 2017-11-07.
