### ISSUE TITLE
Exception in AfterClassSteps is not shown if there is an exception in BeforeClassSteps

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#78]
### Expected behavior
Exception in AfterClassSteps should be shown even if there is an exception in BeforeClassSteps

### Actual behavior
Exception in AfterClassSteps is not shown if there is an exception in BeforeClassSteps

### Steps to reproduce
1. Create a spec
2. Add the following hooks
```
    @BeforeClassSteps
    public void BeforeClassSteps(ExecutionContext context) throws Exception {
        throw new Exception("before class steps ");
    }

    @AfterClassSteps
    public void AfterClassSteps(ExecutionContext context) throws Exception {
        throw new Exception("after class steps ");
    }
```

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by mahendrakariya** [comment]
`AfterClassSteps` and `BeforeClassSteps` are deprecated and we don't expect the users to use these annotations.
