### ISSUE TITLE
Failure in before suite, statistics displayed are wrong

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#79]
**Expected Behavior**
The statistics displayed should be in sync with the ones displayed on the console.

**Actual Behavior**
The statistics in report is

```
0 TOTAL SPECS 0 FAILED 0 PASSED 0 SKIPPED
```

The statistics on the console is

```
Specifications: 0 executed  0 passed    0 failed    1 skipped
Scenarios:  0 executed  0 passed    0 failed    1 skipped
```

**Steps to replicate**
1. Create a spec with scenarios
2. Implement the before suite hook

```
    @BeforeSuite
    public void B1() throws Exception {
        throw new Exception("here1");
    }
```

**Version**

```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by mahendrakariya** [comment]
This has been fixed for quite some time. @sguptatw You can test this on the latest available nightly build.
