### ISSUE TITLE
Add spec file name and step line number in case of failure

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#81]
### Expected behavior

On failure the report should indicate the spec file name and the line number where the failure occured.
### Steps to reproduce
1. Create a spec with an exception in one of the steps
2. The failure indicates the spec name. 
3. The request is to indicate the spec file name and the line number where the failure occured.
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by mahendrakariya** [comment]
@sguptatw Console report has this information. Could you please clarify on how exactly would you like to see this info in HTML reports? 

Moreover, HTML reports shows the entire spec file and clearly highlights the failed step. How will this particular info enhance the UX?

**Comment by apoorvam** [comment]
Currently, HTML report shows the spec file path and also bubbles up the failed scenarios. 

Is this issue still valid? @sguptatw
