### ISSUE TITLE
Filtering of tags giving wrong result

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#82]
**Expected Behavior**
Filtering of the tag on a scenario should result in the specfic scenario.

**Actual Behavior**
It is listing all scenarios under the spec

**Steps to replicate**
1. Create a spec
```
c Heading
=====================
tags:top


c
-----------------------------
tags: something

* step1

c1
-----------------------------
tags:scenario3 ppp a b c d e f g h i j k l m n o p q r s t u v w x y z

* step1
```
2. Give the implementation
```
    @Step("step1")
    public void implementation2() throws Exception {
        throw new Exception("ghjsdf");

    }
```
3. Execute the spec
4. Check the result html
5. filter by tag `something`.
6. It lists both the scenarios.

**Version**
```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by kaustavdm** [comment]
Fix should be available in html-report nightly >= 2016-06-27.
