### ISSUE TITLE
Scenario status icon not shown in table driven execution

### ISSUE THREAD

**Issue by apoorvam** [getgauge/html-report#83]
The circle showing status of test is not shown in case of passed scenarios in Table driven exe.
![screen shot 2016-06-13 at 4 07 07 pm](https://cloud.githubusercontent.com/assets/8859725/16004746/1620ee72-3181-11e6-872b-4eda1f7960d8.png)

**Comment by kaustavdm** [comment]
This works now. Should be available in html-report nightly >= 2016-06-30.

<img width="628" alt="gauge show scenario status" src="https://cloud.githubusercontent.com/assets/364832/16481877/fb99a970-3eca-11e6-8376-fb5c4012c781.png">
