### ISSUE TITLE
The report can indicate the gauge -v details against which this has been generated

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#84]
Like the environment details, it will also be nice to see the gauge -v details against which this report has been generated.
### Gauge version

```
Gauge version: 0.5.1.nightly-2016-06-16

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-16)
m2h (0.0.1)
xml-report (0.1.2.nightly-2016-05-27)
```

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
