### ISSUE TITLE
Not getting Screenshots in HTML Report on Jenkins - using selenium grid for execution

### ISSUE THREAD

**Issue by Pihu14** [getgauge/html-report#85]
### Expected behavior

Get Screenshots of Failed Test cases on Jenkins Gauge Report .
### Actual behavior

I am Not seeing the screenshots on Gauge Reports on jenkins . The Execution is done using selenium Grid master Slave Config .
Local Reports have screenshots in them .
### Gauge version

Jenkins Master machine Gauge config 
Gauge 0.5.0

**Comment by Pihu14** [comment]
Failed to take regular screenshot: headless environment[runner: 2] . This is seen in Jenkins log

**Comment by kaustavdm** [comment]
This is not a html-report issue, though the issue affects the report. This is related to the screenshot implementation used in the tests. By default, Gauge uses `gauge_screenshot` tool to take a screenshot of the current desktop. It does not work in a headless environment.

To solve this, you will need to implement a [custom screenshot grabber](http://getgauge.io/documentation/user/current/language_features/custom_screenshots.html) in your tests.

**Comment by mahendrakariya** [comment]
@Pihu14 Did the custom screenshot approach work for you?

**Comment by mahendrakariya** [comment]
@Pihu14 Since there is no response, I am assuming your problem has been resolved. 
Please feel free to reopen this issue, if required.
