### ISSUE TITLE
BeforeSpec hook failure marks spec as skipped in sidebar

### ISSUE THREAD

**Issue by kaustavdm** [getgauge/html-report#87]
If a spec has a failure in its before spec hook, html-report adds it to the list of "Failed" specs. But the sidebar entry for the spec shows grey, instead of red.

<img width="916" alt="screen shot 2016-07-27 at 11 14 50 am" src="https://cloud.githubusercontent.com/assets/364832/17165157/07a55fda-53ec-11e6-9452-03461fbd337a.png">

**Comment by mahendrakariya** [comment]
This has been fixed for a long time now. @sguptatw You can test on the latest available nightly build.
