### ISSUE TITLE
Spelling of "Step implementation" is "Step implemenatation"

### ISSUE THREAD

**Issue by pradnyasamant** [getgauge/html-report#93]
### Expected behavior
The report should read 
"Step implementation not found"

### Actual behavior
Report reads
"Step implemenatation not found"

### Steps to reproduce
1. run any spec which has an unimplemented step
2.
3.

### Gauge version
```
2.1.
```

**Comment by mahendrakariya** [comment]
This issue was moved to getgauge/gauge#517
