### ISSUE TITLE
[Test Case] Html re-write

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#96]
The report should be consistent in a sequential/parallel run.

**Header Section**
- [ ] Clicking the Gauge logo should take the user to the Gauge website.
- [ ] What does the Home icon represent?
- [ ] The Project name should be displayed
- [ ] If the Gauge specs have been executed with tags, where does the tags get displayed?

**Main Section**
> The Default view
>> The Graph
>>>- [ ] By default the Graph is displayed 
>>>- [ ] The graph is plotted with the success, failure and skipped statistics of the specification.

>> The env details
>>>- [ ] How is the success rate calculated?
>>>- [ ] Total time of the execution is displayed.
>>>- [ ] The date and time of the report generation is displayed

>> The Statistics
>>>- [ ] Should show spec statistics

**LHS**
> Filter Section based on
>> - [ ] Specification level tag
>> - [ ] Scenario level tag
>> - [ ] How does the hook level tags get filtered?
>> - [ ] `something` should match partial keys`something else`, `something more`....
>> - [ ] Specification name

> Search in
>> - [ ] Need more details

> Specification list
>> - [ ] [Nested specifications](https://github.com/getgauge/html-report/issues/99)

> - [ ] On clicking the specification folder, the default view of the main page should be displayed

**RHS**
> Specification Details
>> - [ ] The specification heading should be displayed
>> - [ ] The scenarios should be displayed in the order failed, skipped, passed 
>> - [ ] The path of the specification to be displayed.
>> - [ ] If there is a data table at the spec level, then the details are to be displayed for every row.
>> - [ ] If a scenario is not using the data table details then it should be displayed separately.

**Comment by apoorvam** [comment]
@sguptatw Is this for you to verify during testing? Is it a testcase to be added in functional tests?

**Comment by sguptatw** [comment]
@apoorvam :This is just for my verification.

**Comment by sguptatw** [comment]
This is not relevant anymore
