### ISSUE TITLE
[Rewrite] Filter should consider spec level tags

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#97]
**Expected Behavior**
Filter should consider spec level tags

**Actual behavior**
Filter is considering scenario level tags and not spec level tags

**Steps to replicate**
1. Create a spec

```
something else
=====================
tags:top

not
---------------------------

tags: single word

* something
```
1. Create an implementation

```
    @Step("something")
    public void implementation1() {
}
```
1. Execute the specs and open the html-report
2. Search for `top`
   There are no specs getting listed

**Version**

```
Gauge version: 0.6.3.nightly-2016-10-25

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-10-26)
java (0.5.1.nightly-2016-10-21)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by mahendrakariya** [comment]
Fix available in nightly >= 2016-11-09
