### ISSUE TITLE
[Rewrite] Filter criteria should match partial keys

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#98]
**Expected behavior**
Filter criteria `something` should match `something else`, `something more`....

**Actual behavior**
Filter criteria is matching the exact criteria

**Steps to replicate**
1. Create a spec 

```
something more
=====================
tags:done

not
---------------------------

tags: nothing

* something
```
1. Create another spec

```
something else
=====================
tags:top

not
---------------------------

tags: single word

* something
```
1. When I filter with criteria `something`, it should match specs `something else` and `something more`

**version**

```
Gauge version: 0.6.3.nightly-2016-10-25

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-10-26)
java (0.5.1.nightly-2016-10-21)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by mahendrakariya** [comment]
Fix available in nightly >= 2016-11-09

**Comment by sguptatw** [comment]
How should the filter work on tags?
If there are tags `nothing more` and `nothing else` - should the filter criteria `nothing` list both?
